/**
 * Canonical audit action names for Sanctuary Protected.
 * Prefer these constants everywhere — do not invent ad-hoc strings.
 */
export const AuditAction = {
  CHURCH_CREATED: "church.created",
  CHURCH_SETTINGS_UPDATED: "church.settings_updated",
  CHURCH_SETTINGS_GENERAL_UPDATED: "church.settings.general_updated",
  CHURCH_SETTINGS_CONTACT_UPDATED: "church.settings.contact_updated",
  CHURCH_CONTACT_CREATED: "church.contact_created",
  CHURCH_CONTACT_UPDATED: "church.contact_updated",
  CHURCH_CONTACT_REMOVED: "church.contact_removed",
  CHURCH_SETTINGS_ADDRESS_UPDATED: "church.settings.address_updated",
  CHURCH_SETTINGS_BRANDING_UPDATED: "church.settings.branding_updated",
  CHURCH_SETTINGS_SECURITY_UPDATED: "church.settings.security_updated",
  CHURCH_SETTINGS_PREFERENCES_UPDATED: "church.settings.preferences_updated",
  CHURCH_THREAT_LEVEL_UPDATED: "church.threat_level_updated",
  CHURCH_THREAT_LEVEL_EDITED: "church.threat_level_edited",
  CHURCH_THREAT_LEVEL_DELETED: "church.threat_level_deleted",
  CHURCH_LOGO_UPDATED: "church.logo_updated",
  CHURCH_ACCOUNT_SUSPENDED: "church.account_suspended",
  CHURCH_ACCOUNT_REACTIVATED: "church.account_reactivated",
  CHURCH_ACCOUNT_CLOSED: "church.account_closed",
  CAMPUS_CREATED: "campus.created",
  CAMPUS_UPDATED: "campus.updated",
  CAMPUS_STATUS_CHANGED: "campus.status_changed",
  CAMPUS_PRIMARY_CHANGED: "campus.primary_changed",
  CAMPUS_ARCHIVED: "campus.archived",
  CAMPUS_DEACTIVATED: "campus.deactivated",
  CAMPUS_REACTIVATED: "campus.reactivated",
  CAMPUS_DELETED: "campus.deleted",
  CAMPUS_DELEGATION_ADDED: "campus.delegation_added",
  CAMPUS_DELEGATION_REMOVED: "campus.delegation_removed",
  CAMPUS_DELEGATION_EXTENDED: "campus.delegation_extended",
  CAMPUS_DELEGATION_EXPIRED: "campus.delegation_expired",
  CAMPUS_UNAUTHORIZED_ATTEMPT: "campus.unauthorized_attempt",
  CAMPUS_PRIVILEGE_ESCALATION_ATTEMPT: "campus.privilege_escalation_attempt",
  CAMPUS_MEMBERSHIP_ADDED: "campus_membership.added",
  CAMPUS_MEMBERSHIP_REMOVED: "campus_membership.removed",
  CAMPUS_MEMBERSHIP_ROLE_CHANGED: "campus_membership.role_changed",
  CAMPUS_MEMBERSHIP_PRIMARY_CHANGED: "campus_membership.primary_changed",
  MEMBER_INVITED: "member.invited",
  MEMBER_PROVISIONED: "member.provisioned",
  INVITATION_RESENT: "invitation.resent",
  INVITATION_REVOKED: "invitation.revoked",
  INVITATION_ACCEPTED: "invitation.accepted",
  MEMBERSHIP_ROLE_CHANGED: "membership.role_changed",
  MEMBERSHIP_SUSPENDED: "membership.suspended",
  MEMBERSHIP_REMOVED: "membership.removed",
  MEMBERSHIP_REACTIVATED: "membership.reactivated",
  MEMBER_PROFILE_UPDATED: "member.profile_updated",
  OWNERSHIP_TRANSFER_INITIATED: "ownership.transfer_initiated",
  OWNERSHIP_TRANSFER_COMPLETED: "ownership.transfer_completed",
  AUTH_LOGIN: "auth.login",
  AUTH_MFA_CHALLENGE_SENT: "auth.mfa_challenge_sent",
  AUTH_MFA_VERIFIED: "auth.mfa_verified",
  AUTH_MFA_FAILED: "auth.mfa_failed",
  AUTH_MFA_PHONE_VERIFIED: "auth.mfa_phone_verified",
  AUTH_MFA_PHONE_REMOVED: "auth.mfa_phone_removed",
  DEVICE_VERIFICATION_REQUIRED: "auth.device_verification_required",
  DEVICE_VERIFICATION_SUCCEEDED: "auth.device_verification_succeeded",
  TRUSTED_DEVICE_CREATED: "auth.trusted_device_created",
  TRUSTED_DEVICE_USED: "auth.trusted_device_used",
  TRUSTED_DEVICE_REVOKED: "auth.trusted_device_revoked",
  ALL_TRUSTED_DEVICES_REVOKED: "auth.all_trusted_devices_revoked",
  TRUSTED_DEVICE_EXPIRED: "auth.trusted_device_expired",
  TRUSTED_DEVICE_VALIDATION_FAILED: "auth.trusted_device_validation_failed",
  PLATFORM_MFA_ENABLED: "platform.mfa_enabled",
  PLATFORM_MFA_DISABLED: "platform.mfa_disabled",
  ORGANIZATION_MFA_ENABLED: "organization.mfa_enabled",
  ORGANIZATION_MFA_DISABLED: "organization.mfa_disabled",
  PLATFORM_MFA_REAUTH_REQUIRED: "platform.mfa_reauth_required",
  ORGANIZATION_MFA_REAUTH_REQUIRED: "organization.mfa_reauth_required",
  MFA_EMERGENCY_OVERRIDE_ACTIVE: "platform.mfa_emergency_override_active",
  INCIDENT_CREATED: "incident.created",
  INCIDENT_UPDATED: "incident.updated",
  INCIDENT_MEMBER_ADDED: "incident.member_added",
  INCIDENT_MEMBER_REMOVED: "incident.member_removed",
  INCIDENT_PHOTO_ADDED: "incident.photo_added",
  INCIDENT_PHOTO_REMOVED: "incident.photo_removed",
  EQUIPMENT_CREATED: "equipment.created",
  EQUIPMENT_UPDATED: "equipment.updated",
  EQUIPMENT_STATUS_CHANGED: "equipment.status_changed",
  EQUIPMENT_ARCHIVED: "equipment.archived",
  EQUIPMENT_RESTORED: "equipment.restored",
  EQUIPMENT_ASSIGNED: "equipment.assigned",
  EQUIPMENT_RETURNED: "equipment.returned",
  EQUIPMENT_REPORTED_LOST: "equipment.reported_lost",
  EQUIPMENT_REPORTED_STOLEN: "equipment.reported_stolen",
  EQUIPMENT_MAINTENANCE_SCHEDULED: "equipment.maintenance_scheduled",
  EQUIPMENT_MAINTENANCE_COMPLETED: "equipment.maintenance_completed",
  EQUIPMENT_INSPECTION_FAILED: "equipment.inspection_failed",
  EQUIPMENT_ATTACHMENT_UPLOADED: "equipment.attachment_uploaded",
  EQUIPMENT_ATTACHMENT_REMOVED: "equipment.attachment_removed",
  EQUIPMENT_RELATIONSHIP_ADDED: "equipment.relationship_added",
  EQUIPMENT_RELATIONSHIP_REMOVED: "equipment.relationship_removed",
  MEDICAL_SUPPLY_CREATED: "medical_supply.created",
  MEDICAL_SUPPLY_UPDATED: "medical_supply.updated",
  MEDICAL_SUPPLY_ARCHIVED: "medical_supply.archived",
  MEDICAL_SUPPLY_RESTORED: "medical_supply.restored",
  MEDICAL_SUPPLY_USED: "medical_supply.used",
  MEDICAL_SUPPLY_USAGE_REMOVED: "medical_supply.usage_removed",
  SAFETY_CONCERN_PROFILE_CREATED: "safety_concern.profile_created",
  SAFETY_CONCERN_PROFILE_UPDATED: "safety_concern.profile_updated",
  SAFETY_CONCERN_PROFILE_ARCHIVED: "safety_concern.profile_archived",
  SAFETY_CONCERN_PROFILE_RESTORED: "safety_concern.profile_restored",
  SAFETY_CONCERN_PHOTO_UPLOADED: "safety_concern.photo_uploaded",
  SAFETY_CONCERN_PHOTO_ARCHIVED: "safety_concern.photo_archived",
  SAFETY_CONCERN_INCIDENT_LINKED: "safety_concern.incident_linked",
  SAFETY_CONCERN_INCIDENT_UNLINKED: "safety_concern.incident_unlinked",
  SAFETY_CONCERN_REVIEW_COMPLETED: "safety_concern.review_completed",
  SAFETY_CONCERN_RESTRICTION_UPDATED: "safety_concern.restriction_updated",
  SAFETY_CONCERN_SETTINGS_UPDATED: "safety_concern.settings_updated",
  CERTIFICATION_CREATED: "certification.created",
  CERTIFICATION_UPDATED: "certification.updated",
  CERTIFICATION_ARCHIVED: "certification.archived",
  CERTIFICATION_DELETED: "certification.deleted",
  NOTIFICATION_CREATED: "notification.created",
  NOTIFICATION_QUEUED: "notification.queued",
  NOTIFICATION_CANCELLED: "notification.cancelled",
  NOTIFICATION_ACKNOWLEDGED: "notification.acknowledged",
  NOTIFICATION_DELIVERY_SENT: "notification.delivery_sent",
  NOTIFICATION_DELIVERY_FAILED: "notification.delivery_failed",
  NOTIFICATION_DELIVERY_RETRIED: "notification.delivery_retried",
  NOTIFICATION_PREFERENCES_UPDATED: "notification.preferences_updated",
  NOTIFICATION_SETTINGS_UPDATED: "notification.settings_updated",
  NOTIFICATION_TEMPLATE_CREATED: "notification.template_created",
  NOTIFICATION_TEMPLATE_UPDATED: "notification.template_updated",
  NOTIFICATION_TEMPLATE_RESTORED: "notification.template_restored",
  NOTIFICATION_TEST_EMAIL_SENT: "notification.test_email_sent",
  EMAIL_SENDER_CONFIGURATION_VIEWED: "email.sender_configuration_viewed",
  EMAIL_SENDER_TEST_SENT: "email.sender_test_sent",
  EMAIL_SENDER_TEST_FAILED: "email.sender_test_failed",
  EMAIL_SENDER_CATEGORY_CHANGED: "email.sender_category_changed",
  EMAIL_DELIVERY_SENDER_RESOLVED: "email.delivery_sender_resolved",
  EMAIL_DELIVERY_SENDER_FALLBACK_USED: "email.delivery_sender_fallback_used",
  EMAIL_DELIVERY_SENDER_REJECTED: "email.delivery_sender_rejected",
  NOTIFICATION_GROUP_CREATED: "notification_group.created",
  NOTIFICATION_GROUP_UPDATED: "notification_group.updated",
  NOTIFICATION_GROUP_ARCHIVED: "notification_group.archived",
  NOTIFICATION_GROUP_MEMBER_ADDED: "notification_group.member_added",
  NOTIFICATION_GROUP_MEMBER_REMOVED: "notification_group.member_removed",
  NOTIFICATION_GROUP_CHILD_ADDED: "notification_group.child_group_added",
  NOTIFICATION_GROUP_CHILD_REMOVED: "notification_group.child_group_removed",
  NOTIFICATION_GROUP_NESTING_REJECTED: "notification_group.nesting_rejected",
  NOTIFICATION_GROUP_DEFAULTS_UPDATED: "notification_group.defaults_updated",
  NOTIFICATION_ENDPOINT_ADDED: "notification.endpoint_added",
  NOTIFICATION_ENDPOINT_VERIFIED: "notification.endpoint_verified",
  NOTIFICATION_ENDPOINT_DISABLED: "notification.endpoint_disabled",
  NOTIFICATION_SMS_OPTED_IN: "notification.sms_opted_in",
  NOTIFICATION_SMS_OPTED_OUT: "notification.sms_opted_out",
  POLICY_CREATED: "policy.created",
  POLICY_UPDATED: "policy.updated",
  POLICY_SUBMITTED: "policy.submitted",
  POLICY_CHANGES_REQUESTED: "policy.changes_requested",
  POLICY_APPROVED: "policy.approved",
  POLICY_PUBLISHED: "policy.published",
  POLICY_RETIRED: "policy.retired",
  POLICY_ARCHIVED: "policy.archived",
  POLICY_RESTORED: "policy.restored",
  POLICY_REVISION_STARTED: "policy.revision_started",
  POLICY_ATTACHMENT_UPLOADED: "policy.attachment_uploaded",
  POLICY_ATTACHMENT_REMOVED: "policy.attachment_removed",
  POLICY_ACKNOWLEDGED: "policy.acknowledged",
  POLICY_ACKNOWLEDGMENT_VIEWED: "policy.acknowledgment_viewed",
  POLICY_ACKNOWLEDGMENT_WAIVED: "policy.acknowledgment_waived",
  POLICY_ACKNOWLEDGMENTS_ASSIGNED: "policy.acknowledgments_assigned",
  POLICY_ASSIGNMENT_ADDED: "policy.assignment_added",
  POLICY_ASSIGNMENT_REVOKED: "policy.assignment_revoked",
  SCHEDULE_EVENT_CREATED: "schedule.event_created",
  SCHEDULE_EVENT_UPDATED: "schedule.event_updated",
  SCHEDULE_EVENT_CANCELLED: "schedule.event_cancelled",
  SCHEDULE_EVENT_COMPLETED: "schedule.event_completed",
  SCHEDULE_SHIFT_CREATED: "schedule.shift_created",
  SCHEDULE_SHIFT_UPDATED: "schedule.shift_updated",
  SCHEDULE_SHIFT_CANCELLED: "schedule.shift_cancelled",
  SCHEDULE_ASSIGNMENT_CREATED: "schedule.assignment_created",
  SCHEDULE_ASSIGNMENT_ACCEPTED: "schedule.assignment_accepted",
  SCHEDULE_ASSIGNMENT_DECLINED: "schedule.assignment_declined",
  SCHEDULE_ASSIGNMENT_CANCELLED: "schedule.assignment_cancelled",
  SCHEDULE_ASSIGNMENT_OVERRIDE: "schedule.assignment_override",
  SCHEDULE_UNAVAILABILITY_CREATED: "schedule.unavailability_created",
  SCHEDULE_UNAVAILABILITY_UPDATED: "schedule.unavailability_updated",
  SCHEDULE_UNAVAILABILITY_CANCELLED: "schedule.unavailability_cancelled",
  SCHEDULE_SETTINGS_UPDATED: "schedule.settings_updated",
  SCHEDULE_TEMPLATE_CREATED: "schedule.template_created",
  SCHEDULE_TEMPLATE_UPDATED: "schedule.template_updated",
  SCHEDULE_TEMPLATE_ARCHIVED: "schedule.template_archived",
  SCHEDULE_TEMPLATE_APPLIED: "schedule.template_applied",
  DASHBOARD_BOX_SETTINGS_UPDATED: "dashboard.box_settings_updated",
  DASHBOARD_BOX_SETTING_RESET: "dashboard.box_setting_reset",
  DASHBOARD_BOX_SETTINGS_RESET_ALL: "dashboard.box_settings_reset_all",
  SUBSCRIPTION_CREATED: "subscription.created",
  SUBSCRIPTION_ACTIVATED: "subscription.activated",
  SUBSCRIPTION_PLAN_CHANGED: "subscription.plan_changed",
  SUBSCRIPTION_STATUS_CHANGED: "subscription.status_changed",
  SUBSCRIPTION_TRIAL_STARTED: "subscription.trial_started",
  SUBSCRIPTION_CANCELLED: "subscription.cancelled",
  SUBSCRIPTION_REACTIVATED: "subscription.reactivated",
  PLATFORM_BOOTSTRAP_SUPER_ADMIN_CREATED: "platform.bootstrap_super_admin_created",
  PLATFORM_ACCOUNT_INVITED: "platform.account_invited",
  PLATFORM_ACCOUNT_CREATED: "platform.account_created",
  PLATFORM_ACCOUNT_UPDATED: "platform.account_updated",
  PLATFORM_ACCOUNT_DISABLED: "platform.account_disabled",
  PLATFORM_ACCOUNT_RESTORED: "platform.account_restored",
  PLATFORM_ROLE_ASSIGNED: "platform.role_assigned",
  PLATFORM_ROLE_REVOKED: "platform.role_revoked",
  PLATFORM_SUPER_ADMIN_CREATED: "platform.super_admin_created",
  PLATFORM_SUPER_ADMIN_REMOVED: "platform.super_admin_removed",
  PLATFORM_PASSWORD_RESET_REQUIRED: "platform.password_reset_required",
  PLATFORM_MFA_REQUIRED: "platform.mfa_required",
  PLATFORM_MFA_ENROLLED: "platform.mfa_enrolled",
  PLATFORM_LOGIN_SUCCEEDED: "platform.login_succeeded",
  PLATFORM_LOGIN_FAILED: "platform.login_failed",
  PLATFORM_CHURCH_VIEWED: "platform.church_viewed",
  PLATFORM_CHURCH_UPDATED: "platform.church_updated",
  PLATFORM_CHURCH_SUSPENDED: "platform.church_suspended",
  PLATFORM_CHURCH_RESTORED: "platform.church_restored",
  PLATFORM_SUPPORT_SESSION_STARTED: "platform.support_session_started",
  PLATFORM_SUPPORT_SESSION_ENDED: "platform.support_session_ended",
  PLATFORM_SUBSCRIPTION_PLAN_CHANGED: "platform.subscription_plan_changed",
  PLATFORM_SUBSCRIPTION_CANCELLED: "platform.subscription_cancelled",
  PLATFORM_SUBSCRIPTION_RESTORED: "platform.subscription_restored",
  PLATFORM_ENTITLEMENT_OVERRIDE_CREATED: "platform.entitlement_override_created",
  PLATFORM_ENTITLEMENT_OVERRIDE_REVOKED: "platform.entitlement_override_revoked",
  PLATFORM_JOB_RETRIED: "platform.job_retried",
  PLATFORM_WEBHOOK_RETRIED: "platform.webhook_retried",
  PLATFORM_TEST_EMAIL_SENT: "platform.test_email_sent",
  PLATFORM_TEST_SMS_SENT: "platform.test_sms_sent",
  DEMO_ORGANIZATION_MARKED_DEMO: "demo_organization.marked_demo",
  DEMO_ORGANIZATION_RESTORE_ENABLED: "demo_organization.restore_enabled",
  DEMO_ORGANIZATION_RESTORE_DISABLED: "demo_organization.restore_disabled",
  DEMO_ORGANIZATION_LOCKED: "demo_organization.locked",
  DEMO_ORGANIZATION_UNLOCKED: "demo_organization.unlocked",
  DEMO_ORGANIZATION_MAINTENANCE_ON: "demo_organization.maintenance_on",
  DEMO_ORGANIZATION_MAINTENANCE_OFF: "demo_organization.maintenance_off",
  DEMO_SNAPSHOT_CREATED: "demo_snapshot.created",
  DEMO_SNAPSHOT_SET_DEFAULT: "demo_snapshot.set_default",
  DEMO_SNAPSHOT_PROTECTED: "demo_snapshot.protected",
  DEMO_SNAPSHOT_UNPROTECTED: "demo_snapshot.unprotected",
  DEMO_SNAPSHOT_ARCHIVED: "demo_snapshot.archived",
  DEMO_SNAPSHOT_METADATA_UPDATED: "demo_snapshot.metadata_updated",
  DEMO_SNAPSHOT_DELETED: "demo_snapshot.deleted",
  DEMO_SNAPSHOT_RETENTION_APPLIED: "demo_snapshot.retention_applied",
  DEMO_RESTORE_COMPLETED: "demo_restore.completed",
  DEMO_RESTORE_FAILED: "demo_restore.failed",
  DEMO_RESTORE_ROLLED_BACK: "demo_restore.rolled_back",
  DEMO_RESTORE_MANUAL_ROLLBACK: "demo_restore.manual_rollback",
  DEMO_RESTORE_EMERGENCY_UNLOCK: "demo_restore.emergency_unlock",
  DEMO_RESTORE_LOCK_EXPIRED: "demo_restore.lock_expired",
  DEMO_RESTORE_RECOVERY: "demo_restore.recovery",
  HELP_CATEGORY_CREATED: "help.category_created",
  HELP_CATEGORY_UPDATED: "help.category_updated",
  HELP_CATEGORY_ARCHIVED: "help.category_archived",
  HELP_CATEGORY_DELETED: "help.category_deleted",
  HELP_ARTICLE_CREATED: "help.article_created",
  HELP_ARTICLE_UPDATED: "help.article_updated",
  HELP_ARTICLE_SUBMITTED: "help.article_submitted",
  HELP_ARTICLE_PUBLISHED: "help.article_published",
  HELP_ARTICLE_ARCHIVED: "help.article_archived",
  HELP_ARTICLE_RESTORED: "help.article_restored",
  HELP_ARTICLE_DELETED: "help.article_deleted",
  HELP_ARTICLE_VERSION_RESTORED: "help.article_version_restored",
  HELP_ARTICLE_REVIEW_DUE_SET: "help.article_review_due_set",
  HELP_STEP_CREATED: "help.step_created",
  HELP_STEP_UPDATED: "help.step_updated",
  HELP_STEP_DELETED: "help.step_deleted",
  TRAINING_EVENT_CREATED: "training.event_created",
  TRAINING_EVENT_UPDATED: "training.event_updated",
  TRAINING_EVENT_CANCELLED: "training.event_cancelled",
  TRAINING_COMPLETION_RECORDED: "training.completion_recorded",
  TRAINING_SETTINGS_UPDATED: "training.settings_updated",
  TRAINING_EXTERNAL_VERIFIED: "training.external_verified",
} as const;

export type AuditActionName = (typeof AuditAction)[keyof typeof AuditAction];

export const AuditEntityType = {
  CHURCH: "church",
  CAMPUS: "campus",
  CAMPUS_MEMBERSHIP: "campus_membership",
  CHURCH_INVITATION: "church_invitation",
  CHURCH_MEMBERSHIP: "church_membership",
  CHURCH_CONTACT: "church_contact",
  CHURCH_THREAT_LEVEL: "church_threat_level",
  USER: "user",
  TRUSTED_DEVICE: "trusted_device",
  INCIDENT: "incident",
  INCIDENT_MEMBER: "incident_member",
  INCIDENT_ATTACHMENT: "incident_attachment",
  SECURITY_EQUIPMENT: "security_equipment",
  EQUIPMENT_ASSIGNMENT: "equipment_assignment",
  EQUIPMENT_MAINTENANCE: "equipment_maintenance",
  EQUIPMENT_ATTACHMENT: "equipment_attachment",
  EQUIPMENT_RELATIONSHIP: "equipment_relationship",
  MEDICAL_SUPPLY: "medical_supply",
  MEDICAL_SUPPLY_USAGE: "medical_supply_usage",
  SAFETY_CONCERN_PROFILE: "safety_concern_profile",
  SAFETY_CONCERN_PHOTO: "safety_concern_photo",
  SAFETY_CONCERN_INCIDENT: "safety_concern_incident",
  SAFETY_CONCERN_REVIEW: "safety_concern_review",
  SAFETY_CONCERN_SETTINGS: "safety_concern_settings",
  CERTIFICATION: "certification",
  NOTIFICATION: "notification",
  NOTIFICATION_DELIVERY: "notification_delivery",
  NOTIFICATION_TEMPLATE: "notification_template",
  NOTIFICATION_SETTINGS: "notification_settings",
  NOTIFICATION_GROUP: "notification_group",
  NOTIFICATION_ENDPOINT: "notification_endpoint",
  EMAIL_SENDER: "email_sender",
  POLICY_DOCUMENT: "policy_document",
  POLICY_VERSION: "policy_version",
  POLICY_APPROVAL: "policy_approval",
  POLICY_ATTACHMENT: "policy_attachment",
  POLICY_ACKNOWLEDGMENT: "policy_acknowledgment",
  POLICY_ASSIGNMENT: "policy_assignment",
  SCHEDULE_EVENT: "schedule_event",
  SCHEDULE_SHIFT: "schedule_shift",
  SHIFT_ASSIGNMENT: "shift_assignment",
  MEMBER_UNAVAILABILITY: "member_unavailability",
  SCHEDULE_SETTINGS: "schedule_settings",
  SCHEDULE_TEMPLATE: "schedule_template",
  DASHBOARD_BOX_SETTINGS: "dashboard_box_settings",
  CHURCH_SUBSCRIPTION: "church_subscription",
  SUBSCRIPTION_PLAN: "subscription_plan",
  PLATFORM_ACCOUNT: "platform_account",
  PLATFORM_SECURITY_SETTINGS: "platform_security_settings",
  ORGANIZATION_SECURITY_SETTINGS: "organization_security_settings",
  PLATFORM_ROLE: "platform_role",
  PLATFORM_ACCESS_SESSION: "platform_access_session",
  PLATFORM_INVITATION: "platform_invitation",
  HELP_CATEGORY: "help_category",
  HELP_ARTICLE: "help_article",
  HELP_ARTICLE_STEP: "help_article_step",
  HELP_ARTICLE_VERSION: "help_article_version",
  TRAINING_EVENT: "training_event",
  TRAINING_COMPLETION_RECORD: "training_completion_record",
  TRAINING_EXTERNAL_RECORD: "training_external_record",
  TRAINING_SETTINGS: "training_settings",
} as const;

export type AuditEntityTypeName =
  (typeof AuditEntityType)[keyof typeof AuditEntityType];

export function labelForAuditAction(action: string): string {
  const labels: Record<string, string> = {
    [AuditAction.CHURCH_CREATED]: "Church created",
    [AuditAction.CHURCH_SETTINGS_UPDATED]: "Church settings updated",
    [AuditAction.CHURCH_SETTINGS_GENERAL_UPDATED]: "General settings updated",
    [AuditAction.CHURCH_SETTINGS_CONTACT_UPDATED]: "Contact settings updated",
    [AuditAction.CHURCH_CONTACT_CREATED]: "Church contact created",
    [AuditAction.CHURCH_CONTACT_UPDATED]: "Church contact updated",
    [AuditAction.CHURCH_CONTACT_REMOVED]: "Church contact removed",
    [AuditAction.CHURCH_SETTINGS_ADDRESS_UPDATED]: "Address settings updated",
    [AuditAction.CHURCH_SETTINGS_BRANDING_UPDATED]: "Branding settings updated",
    [AuditAction.CHURCH_SETTINGS_SECURITY_UPDATED]: "Security settings updated",
    [AuditAction.CHURCH_SETTINGS_PREFERENCES_UPDATED]:
      "Application preferences updated",
    [AuditAction.CHURCH_THREAT_LEVEL_UPDATED]: "Threat level updated",
    [AuditAction.CHURCH_THREAT_LEVEL_EDITED]: "Threat level entry edited",
    [AuditAction.CHURCH_THREAT_LEVEL_DELETED]: "Threat level entry deleted",
    [AuditAction.CHURCH_LOGO_UPDATED]: "Church logo updated",
    [AuditAction.CHURCH_ACCOUNT_SUSPENDED]: "Church account suspended",
    [AuditAction.CHURCH_ACCOUNT_REACTIVATED]: "Church account reactivated",
    [AuditAction.CHURCH_ACCOUNT_CLOSED]: "Church account closed",
    [AuditAction.CAMPUS_CREATED]: "Campus created",
    [AuditAction.CAMPUS_UPDATED]: "Campus updated",
    [AuditAction.CAMPUS_STATUS_CHANGED]: "Campus status changed",
    [AuditAction.CAMPUS_PRIMARY_CHANGED]: "Primary campus changed",
    [AuditAction.CAMPUS_ARCHIVED]: "Campus archived",
    [AuditAction.CAMPUS_DEACTIVATED]: "Campus deactivated",
    [AuditAction.CAMPUS_REACTIVATED]: "Campus reactivated",
    [AuditAction.CAMPUS_DELETED]: "Campus deleted",
    [AuditAction.CAMPUS_DELEGATION_ADDED]: "Campus delegated manager added",
    [AuditAction.CAMPUS_DELEGATION_REMOVED]: "Campus delegated manager removed",
    [AuditAction.CAMPUS_DELEGATION_EXTENDED]: "Campus delegation extended",
    [AuditAction.CAMPUS_DELEGATION_EXPIRED]: "Campus delegation expired",
    [AuditAction.CAMPUS_UNAUTHORIZED_ATTEMPT]:
      "Unauthorized campus-management attempt",
    [AuditAction.CAMPUS_PRIVILEGE_ESCALATION_ATTEMPT]:
      "Campus privilege-escalation attempt",
    [AuditAction.CAMPUS_MEMBERSHIP_ADDED]: "Campus membership added",
    [AuditAction.CAMPUS_MEMBERSHIP_REMOVED]: "Campus membership removed",
    [AuditAction.CAMPUS_MEMBERSHIP_ROLE_CHANGED]: "Campus membership role changed",
    [AuditAction.CAMPUS_MEMBERSHIP_PRIMARY_CHANGED]:
      "Campus membership primary changed",
    [AuditAction.MEMBER_INVITED]: "Member invited",
    [AuditAction.MEMBER_PROVISIONED]: "Member provisioned",
    [AuditAction.INVITATION_RESENT]: "Invitation resent",
    [AuditAction.INVITATION_REVOKED]: "Invitation revoked",
    [AuditAction.INVITATION_ACCEPTED]: "Invitation accepted",
    [AuditAction.MEMBERSHIP_ROLE_CHANGED]: "Membership role changed",
    [AuditAction.MEMBERSHIP_SUSPENDED]: "Membership suspended",
    [AuditAction.MEMBERSHIP_REMOVED]: "Membership removed",
    [AuditAction.MEMBERSHIP_REACTIVATED]: "Membership reactivated",
    [AuditAction.MEMBER_PROFILE_UPDATED]: "Member profile updated",
    [AuditAction.OWNERSHIP_TRANSFER_INITIATED]: "Owner transfer initiated",
    [AuditAction.OWNERSHIP_TRANSFER_COMPLETED]: "Owner transfer completed",
    [AuditAction.AUTH_LOGIN]: "User signed in",
    [AuditAction.AUTH_MFA_CHALLENGE_SENT]: "Sign-in verification code sent",
    [AuditAction.AUTH_MFA_VERIFIED]: "Sign-in verification completed",
    [AuditAction.AUTH_MFA_FAILED]: "Sign-in verification failed",
    [AuditAction.AUTH_MFA_PHONE_VERIFIED]: "Backup phone verified",
    [AuditAction.AUTH_MFA_PHONE_REMOVED]: "Backup phone removed",
    [AuditAction.DEVICE_VERIFICATION_REQUIRED]: "Device verification required",
    [AuditAction.DEVICE_VERIFICATION_SUCCEEDED]: "Device verification succeeded",
    [AuditAction.TRUSTED_DEVICE_CREATED]: "Trusted device created",
    [AuditAction.TRUSTED_DEVICE_USED]: "Trusted device used",
    [AuditAction.TRUSTED_DEVICE_REVOKED]: "Trusted device revoked",
    [AuditAction.ALL_TRUSTED_DEVICES_REVOKED]: "All trusted devices revoked",
    [AuditAction.TRUSTED_DEVICE_EXPIRED]: "Trusted device expired",
    [AuditAction.TRUSTED_DEVICE_VALIDATION_FAILED]:
      "Trusted device validation failed",
    [AuditAction.PLATFORM_MFA_ENABLED]: "Platform MFA enabled",
    [AuditAction.PLATFORM_MFA_DISABLED]: "Platform MFA disabled",
    [AuditAction.ORGANIZATION_MFA_ENABLED]: "Organization MFA enabled",
    [AuditAction.ORGANIZATION_MFA_DISABLED]: "Organization MFA disabled",
    [AuditAction.PLATFORM_MFA_REAUTH_REQUIRED]:
      "Platform MFA reauthentication required",
    [AuditAction.ORGANIZATION_MFA_REAUTH_REQUIRED]:
      "Organization MFA reauthentication required",
    [AuditAction.MFA_EMERGENCY_OVERRIDE_ACTIVE]:
      "MFA emergency environment override active",
    [AuditAction.INCIDENT_CREATED]: "Incident created",
    [AuditAction.INCIDENT_UPDATED]: "Incident updated",
    [AuditAction.INCIDENT_MEMBER_ADDED]: "Incident member added",
    [AuditAction.INCIDENT_MEMBER_REMOVED]: "Incident member removed",
    [AuditAction.INCIDENT_PHOTO_ADDED]: "Incident photo added",
    [AuditAction.INCIDENT_PHOTO_REMOVED]: "Incident photo removed",
    [AuditAction.EQUIPMENT_CREATED]: "Equipment created",
    [AuditAction.EQUIPMENT_UPDATED]: "Equipment updated",
    [AuditAction.EQUIPMENT_STATUS_CHANGED]: "Equipment status changed",
    [AuditAction.EQUIPMENT_ARCHIVED]: "Equipment archived",
    [AuditAction.EQUIPMENT_RESTORED]: "Equipment restored",
    [AuditAction.EQUIPMENT_ASSIGNED]: "Equipment assigned",
    [AuditAction.EQUIPMENT_RETURNED]: "Equipment returned",
    [AuditAction.EQUIPMENT_REPORTED_LOST]: "Equipment reported lost",
    [AuditAction.EQUIPMENT_REPORTED_STOLEN]: "Equipment reported stolen",
    [AuditAction.EQUIPMENT_MAINTENANCE_SCHEDULED]: "Equipment maintenance scheduled",
    [AuditAction.EQUIPMENT_MAINTENANCE_COMPLETED]: "Equipment maintenance completed",
    [AuditAction.EQUIPMENT_INSPECTION_FAILED]: "Equipment inspection failed",
    [AuditAction.EQUIPMENT_ATTACHMENT_UPLOADED]: "Equipment attachment uploaded",
    [AuditAction.EQUIPMENT_ATTACHMENT_REMOVED]: "Equipment attachment removed",
    [AuditAction.EQUIPMENT_RELATIONSHIP_ADDED]: "Equipment relationship added",
    [AuditAction.EQUIPMENT_RELATIONSHIP_REMOVED]: "Equipment relationship removed",
    [AuditAction.MEDICAL_SUPPLY_CREATED]: "Medical supply created",
    [AuditAction.MEDICAL_SUPPLY_UPDATED]: "Medical supply updated",
    [AuditAction.MEDICAL_SUPPLY_ARCHIVED]: "Medical supply archived",
    [AuditAction.MEDICAL_SUPPLY_RESTORED]: "Medical supply restored",
    [AuditAction.MEDICAL_SUPPLY_USED]: "Medical supply used on incident",
    [AuditAction.MEDICAL_SUPPLY_USAGE_REMOVED]: "Medical supply usage removed",
    [AuditAction.SAFETY_CONCERN_PROFILE_CREATED]: "Safety concern profile created",
    [AuditAction.SAFETY_CONCERN_PROFILE_UPDATED]: "Safety concern profile updated",
    [AuditAction.SAFETY_CONCERN_PROFILE_ARCHIVED]: "Safety concern profile archived",
    [AuditAction.SAFETY_CONCERN_PROFILE_RESTORED]: "Safety concern profile restored",
    [AuditAction.SAFETY_CONCERN_PHOTO_UPLOADED]: "Safety concern photo uploaded",
    [AuditAction.SAFETY_CONCERN_PHOTO_ARCHIVED]: "Safety concern photo archived",
    [AuditAction.SAFETY_CONCERN_INCIDENT_LINKED]: "Safety concern incident linked",
    [AuditAction.SAFETY_CONCERN_INCIDENT_UNLINKED]: "Safety concern incident unlinked",
    [AuditAction.SAFETY_CONCERN_REVIEW_COMPLETED]: "Safety concern review completed",
    [AuditAction.SAFETY_CONCERN_RESTRICTION_UPDATED]:
      "Safety concern restriction updated",
    [AuditAction.SAFETY_CONCERN_SETTINGS_UPDATED]:
      "Safety concern settings updated",
    [AuditAction.CERTIFICATION_CREATED]: "Certification created",
    [AuditAction.CERTIFICATION_UPDATED]: "Certification updated",
    [AuditAction.CERTIFICATION_ARCHIVED]: "Certification archived",
    [AuditAction.CERTIFICATION_DELETED]: "Certification deleted",
    [AuditAction.NOTIFICATION_CREATED]: "Notification created",
    [AuditAction.NOTIFICATION_QUEUED]: "Notification queued",
    [AuditAction.NOTIFICATION_CANCELLED]: "Notification cancelled",
    [AuditAction.NOTIFICATION_ACKNOWLEDGED]: "Notification acknowledged",
    [AuditAction.NOTIFICATION_DELIVERY_SENT]: "Notification delivery sent",
    [AuditAction.NOTIFICATION_DELIVERY_FAILED]: "Notification delivery failed",
    [AuditAction.NOTIFICATION_DELIVERY_RETRIED]: "Notification delivery retried",
    [AuditAction.NOTIFICATION_PREFERENCES_UPDATED]:
      "Notification preferences updated",
    [AuditAction.NOTIFICATION_SETTINGS_UPDATED]:
      "Notification settings updated",
    [AuditAction.NOTIFICATION_TEMPLATE_CREATED]: "Notification template created",
    [AuditAction.NOTIFICATION_TEMPLATE_UPDATED]: "Notification template updated",
    [AuditAction.NOTIFICATION_TEMPLATE_RESTORED]:
      "Notification template restored",
    [AuditAction.NOTIFICATION_TEST_EMAIL_SENT]: "Test notification email sent",
    [AuditAction.EMAIL_SENDER_CONFIGURATION_VIEWED]:
      "Email sender configuration viewed",
    [AuditAction.EMAIL_SENDER_TEST_SENT]: "Email sender test sent",
    [AuditAction.EMAIL_SENDER_TEST_FAILED]: "Email sender test failed",
    [AuditAction.EMAIL_SENDER_CATEGORY_CHANGED]: "Email sender category changed",
    [AuditAction.EMAIL_DELIVERY_SENDER_RESOLVED]: "Email delivery sender resolved",
    [AuditAction.EMAIL_DELIVERY_SENDER_FALLBACK_USED]:
      "Email delivery sender fallback used",
    [AuditAction.EMAIL_DELIVERY_SENDER_REJECTED]:
      "Email delivery sender rejected",
    [AuditAction.NOTIFICATION_GROUP_CREATED]: "Notification group created",
    [AuditAction.NOTIFICATION_GROUP_UPDATED]: "Notification group updated",
    [AuditAction.NOTIFICATION_GROUP_ARCHIVED]: "Notification group archived",
    [AuditAction.NOTIFICATION_GROUP_MEMBER_ADDED]:
      "Notification group member added",
    [AuditAction.NOTIFICATION_GROUP_MEMBER_REMOVED]:
      "Notification group member removed",
    [AuditAction.NOTIFICATION_GROUP_CHILD_ADDED]:
      "Nested notification group added",
    [AuditAction.NOTIFICATION_GROUP_CHILD_REMOVED]:
      "Nested notification group removed",
    [AuditAction.NOTIFICATION_GROUP_NESTING_REJECTED]:
      "Notification group nesting rejected",
    [AuditAction.NOTIFICATION_GROUP_DEFAULTS_UPDATED]:
      "Notification group defaults updated",
    [AuditAction.NOTIFICATION_ENDPOINT_ADDED]: "Notification endpoint added",
    [AuditAction.NOTIFICATION_ENDPOINT_VERIFIED]:
      "Notification endpoint verified",
    [AuditAction.NOTIFICATION_ENDPOINT_DISABLED]:
      "Notification endpoint disabled",
    [AuditAction.NOTIFICATION_SMS_OPTED_IN]: "Text/SMS notifications opted in",
    [AuditAction.NOTIFICATION_SMS_OPTED_OUT]: "Text/SMS notifications opted out",
    [AuditAction.POLICY_CREATED]: "Policy created",
    [AuditAction.POLICY_UPDATED]: "Policy updated",
    [AuditAction.POLICY_SUBMITTED]: "Policy submitted for review",
    [AuditAction.POLICY_CHANGES_REQUESTED]: "Policy changes requested",
    [AuditAction.POLICY_APPROVED]: "Policy approved",
    [AuditAction.POLICY_PUBLISHED]: "Policy published",
    [AuditAction.POLICY_RETIRED]: "Policy retired",
    [AuditAction.POLICY_ARCHIVED]: "Policy archived",
    [AuditAction.POLICY_RESTORED]: "Policy restored",
    [AuditAction.POLICY_REVISION_STARTED]: "Policy revision started",
    [AuditAction.POLICY_ATTACHMENT_UPLOADED]: "Policy attachment uploaded",
    [AuditAction.POLICY_ATTACHMENT_REMOVED]: "Policy attachment removed",
    [AuditAction.POLICY_ACKNOWLEDGED]: "Policy acknowledged",
    [AuditAction.POLICY_ACKNOWLEDGMENT_VIEWED]: "Policy acknowledgment viewed",
    [AuditAction.POLICY_ACKNOWLEDGMENT_WAIVED]: "Policy acknowledgment waived",
    [AuditAction.POLICY_ACKNOWLEDGMENTS_ASSIGNED]:
      "Policy acknowledgments assigned",
    [AuditAction.POLICY_ASSIGNMENT_ADDED]: "Policy assignment added",
    [AuditAction.POLICY_ASSIGNMENT_REVOKED]: "Policy assignment revoked",
    [AuditAction.SCHEDULE_EVENT_CREATED]: "Schedule event created",
    [AuditAction.SCHEDULE_EVENT_UPDATED]: "Schedule event updated",
    [AuditAction.SCHEDULE_EVENT_CANCELLED]: "Schedule event cancelled",
    [AuditAction.SCHEDULE_EVENT_COMPLETED]: "Schedule event completed",
    [AuditAction.SCHEDULE_SHIFT_CREATED]: "Schedule shift created",
    [AuditAction.SCHEDULE_SHIFT_UPDATED]: "Schedule shift updated",
    [AuditAction.SCHEDULE_SHIFT_CANCELLED]: "Schedule shift cancelled",
    [AuditAction.SCHEDULE_ASSIGNMENT_CREATED]: "Shift assignment created",
    [AuditAction.SCHEDULE_ASSIGNMENT_ACCEPTED]: "Shift assignment accepted",
    [AuditAction.SCHEDULE_ASSIGNMENT_DECLINED]: "Shift assignment declined",
    [AuditAction.SCHEDULE_ASSIGNMENT_CANCELLED]: "Shift assignment cancelled",
    [AuditAction.SCHEDULE_ASSIGNMENT_OVERRIDE]: "Shift assignment conflict override",
    [AuditAction.SCHEDULE_UNAVAILABILITY_CREATED]: "Unavailability created",
    [AuditAction.SCHEDULE_UNAVAILABILITY_UPDATED]: "Unavailability updated",
    [AuditAction.SCHEDULE_UNAVAILABILITY_CANCELLED]: "Unavailability cancelled",
    [AuditAction.SCHEDULE_SETTINGS_UPDATED]: "Scheduling settings updated",
    [AuditAction.SCHEDULE_TEMPLATE_CREATED]: "Schedule template created",
    [AuditAction.SCHEDULE_TEMPLATE_UPDATED]: "Schedule template updated",
    [AuditAction.SCHEDULE_TEMPLATE_ARCHIVED]: "Schedule template archived",
    [AuditAction.SCHEDULE_TEMPLATE_APPLIED]: "Schedule template applied",
    [AuditAction.DASHBOARD_BOX_SETTINGS_UPDATED]:
      "Dashboard box settings updated",
    [AuditAction.DASHBOARD_BOX_SETTING_RESET]: "Dashboard box setting reset",
    [AuditAction.DASHBOARD_BOX_SETTINGS_RESET_ALL]:
      "Dashboard box settings reset to defaults",
    [AuditAction.SUBSCRIPTION_CREATED]: "Subscription created",
    [AuditAction.SUBSCRIPTION_ACTIVATED]: "Subscription activated",
    [AuditAction.SUBSCRIPTION_PLAN_CHANGED]: "Subscription plan changed",
    [AuditAction.SUBSCRIPTION_STATUS_CHANGED]: "Subscription status changed",
    [AuditAction.SUBSCRIPTION_TRIAL_STARTED]: "Subscription trial started",
    [AuditAction.SUBSCRIPTION_CANCELLED]: "Subscription cancelled",
    [AuditAction.SUBSCRIPTION_REACTIVATED]: "Subscription reactivated",
    [AuditAction.PLATFORM_BOOTSTRAP_SUPER_ADMIN_CREATED]:
      "Platform super admin bootstrapped",
    [AuditAction.PLATFORM_ACCOUNT_INVITED]: "Platform account invited",
    [AuditAction.PLATFORM_ACCOUNT_CREATED]: "Platform account created",
    [AuditAction.PLATFORM_ACCOUNT_UPDATED]: "Platform account updated",
    [AuditAction.PLATFORM_ACCOUNT_DISABLED]: "Platform account disabled",
    [AuditAction.PLATFORM_ACCOUNT_RESTORED]: "Platform account restored",
    [AuditAction.PLATFORM_ROLE_ASSIGNED]: "Platform role assigned",
    [AuditAction.PLATFORM_ROLE_REVOKED]: "Platform role revoked",
    [AuditAction.PLATFORM_SUPER_ADMIN_CREATED]: "Platform super admin created",
    [AuditAction.PLATFORM_SUPER_ADMIN_REMOVED]: "Platform super admin removed",
    [AuditAction.PLATFORM_PASSWORD_RESET_REQUIRED]:
      "Platform password reset required",
    [AuditAction.PLATFORM_MFA_REQUIRED]: "Platform MFA required",
    [AuditAction.PLATFORM_MFA_ENROLLED]: "Platform MFA enrolled",
    [AuditAction.PLATFORM_LOGIN_SUCCEEDED]: "Platform login succeeded",
    [AuditAction.PLATFORM_LOGIN_FAILED]: "Platform login failed",
    [AuditAction.PLATFORM_CHURCH_VIEWED]: "Platform church viewed",
    [AuditAction.PLATFORM_CHURCH_UPDATED]: "Platform church updated",
    [AuditAction.PLATFORM_CHURCH_SUSPENDED]: "Platform church suspended",
    [AuditAction.PLATFORM_CHURCH_RESTORED]: "Platform church restored",
    [AuditAction.PLATFORM_SUPPORT_SESSION_STARTED]:
      "Platform support session started",
    [AuditAction.PLATFORM_SUPPORT_SESSION_ENDED]:
      "Platform support session ended",
    [AuditAction.PLATFORM_SUBSCRIPTION_PLAN_CHANGED]:
      "Platform subscription plan changed",
    [AuditAction.PLATFORM_SUBSCRIPTION_CANCELLED]:
      "Platform subscription cancelled",
    [AuditAction.PLATFORM_SUBSCRIPTION_RESTORED]:
      "Platform subscription restored",
    [AuditAction.PLATFORM_ENTITLEMENT_OVERRIDE_CREATED]:
      "Platform entitlement override created",
    [AuditAction.PLATFORM_ENTITLEMENT_OVERRIDE_REVOKED]:
      "Platform entitlement override revoked",
    [AuditAction.PLATFORM_JOB_RETRIED]: "Platform job retried",
    [AuditAction.PLATFORM_WEBHOOK_RETRIED]: "Platform webhook retried",
    [AuditAction.PLATFORM_TEST_EMAIL_SENT]: "Platform test email sent",
    [AuditAction.PLATFORM_TEST_SMS_SENT]: "Platform test Text/SMS sent",
    [AuditAction.DEMO_ORGANIZATION_MARKED_DEMO]: "Demo church marked as demo",
    [AuditAction.DEMO_ORGANIZATION_RESTORE_ENABLED]: "Demo restore enabled",
    [AuditAction.DEMO_ORGANIZATION_RESTORE_DISABLED]: "Demo restore disabled",
    [AuditAction.DEMO_ORGANIZATION_LOCKED]: "Demo church locked",
    [AuditAction.DEMO_ORGANIZATION_UNLOCKED]: "Demo church unlocked",
    [AuditAction.DEMO_ORGANIZATION_MAINTENANCE_ON]: "Demo maintenance on",
    [AuditAction.DEMO_ORGANIZATION_MAINTENANCE_OFF]: "Demo maintenance off",
    [AuditAction.DEMO_SNAPSHOT_CREATED]: "Demo snapshot created",
    [AuditAction.DEMO_SNAPSHOT_SET_DEFAULT]: "Demo snapshot set as default",
    [AuditAction.DEMO_SNAPSHOT_PROTECTED]: "Demo snapshot protected",
    [AuditAction.DEMO_SNAPSHOT_UNPROTECTED]: "Demo snapshot unprotected",
    [AuditAction.DEMO_SNAPSHOT_ARCHIVED]: "Demo snapshot archived",
    [AuditAction.DEMO_SNAPSHOT_METADATA_UPDATED]: "Demo snapshot metadata updated",
    [AuditAction.DEMO_SNAPSHOT_DELETED]: "Demo snapshot deleted",
    [AuditAction.DEMO_SNAPSHOT_RETENTION_APPLIED]:
      "Demo snapshot retention applied",
    [AuditAction.DEMO_RESTORE_COMPLETED]: "Demo restore completed",
    [AuditAction.DEMO_RESTORE_FAILED]: "Demo restore failed",
    [AuditAction.DEMO_RESTORE_ROLLED_BACK]: "Demo restore rolled back",
    [AuditAction.DEMO_RESTORE_MANUAL_ROLLBACK]: "Demo restore manual rollback",
    [AuditAction.DEMO_RESTORE_EMERGENCY_UNLOCK]: "Demo restore emergency unlock",
    [AuditAction.DEMO_RESTORE_LOCK_EXPIRED]: "Demo restore lock expired",
    [AuditAction.DEMO_RESTORE_RECOVERY]: "Demo restore operation recovery",
    [AuditAction.HELP_CATEGORY_CREATED]: "Help category created",
    [AuditAction.HELP_CATEGORY_UPDATED]: "Help category updated",
    [AuditAction.HELP_CATEGORY_ARCHIVED]: "Help category archived",
    [AuditAction.HELP_CATEGORY_DELETED]: "Help category deleted",
    [AuditAction.HELP_ARTICLE_CREATED]: "Help article created",
    [AuditAction.HELP_ARTICLE_UPDATED]: "Help article updated",
    [AuditAction.HELP_ARTICLE_SUBMITTED]: "Help article submitted for review",
    [AuditAction.HELP_ARTICLE_PUBLISHED]: "Help article published",
    [AuditAction.HELP_ARTICLE_ARCHIVED]: "Help article archived",
    [AuditAction.HELP_ARTICLE_RESTORED]: "Help article restored",
    [AuditAction.HELP_ARTICLE_DELETED]: "Help article deleted",
    [AuditAction.HELP_ARTICLE_VERSION_RESTORED]:
      "Help article version restored to draft",
    [AuditAction.HELP_ARTICLE_REVIEW_DUE_SET]: "Help article review due date set",
    [AuditAction.HELP_STEP_CREATED]: "Help step created",
    [AuditAction.HELP_STEP_UPDATED]: "Help step updated",
    [AuditAction.HELP_STEP_DELETED]: "Help step deleted",
    [AuditAction.TRAINING_EVENT_CREATED]: "Training event created",
    [AuditAction.TRAINING_EVENT_UPDATED]: "Training event updated",
    [AuditAction.TRAINING_EVENT_CANCELLED]: "Training event cancelled",
    [AuditAction.TRAINING_COMPLETION_RECORDED]: "Training completion recorded",
    [AuditAction.TRAINING_SETTINGS_UPDATED]: "Training settings updated",
    [AuditAction.TRAINING_EXTERNAL_VERIFIED]: "External training verified",
    // Legacy rows from earlier phases
    "membership.invitation_created": "Member invited",
    "membership.invitation_accepted": "Invitation accepted",
    "membership.status_changed": "Membership status changed",
  };
  return labels[action] ?? action;
}
