/**
 * Canonical audit action names for Sanctuary Protected.
 * Prefer these constants everywhere — do not invent ad-hoc strings.
 */
export const AuditAction = {
  CHURCH_CREATED: "church.created",
  CHURCH_SETTINGS_UPDATED: "church.settings_updated",
  CHURCH_SETTINGS_GENERAL_UPDATED: "church.settings.general_updated",
  CHURCH_SETTINGS_CONTACT_UPDATED: "church.settings.contact_updated",
  CHURCH_CONTACT_CREATED: "church.contact_created",
  CHURCH_CONTACT_UPDATED: "church.contact_updated",
  CHURCH_CONTACT_REMOVED: "church.contact_removed",
  CHURCH_SETTINGS_ADDRESS_UPDATED: "church.settings.address_updated",
  CHURCH_SETTINGS_BRANDING_UPDATED: "church.settings.branding_updated",
  CHURCH_SETTINGS_SECURITY_UPDATED: "church.settings.security_updated",
  CHURCH_SETTINGS_PREFERENCES_UPDATED: "church.settings.preferences_updated",
  CHURCH_THREAT_LEVEL_UPDATED: "church.threat_level_updated",
  CHURCH_LOGO_UPDATED: "church.logo_updated",
  CHURCH_ACCOUNT_SUSPENDED: "church.account_suspended",
  CHURCH_ACCOUNT_REACTIVATED: "church.account_reactivated",
  CHURCH_ACCOUNT_CLOSED: "church.account_closed",
  CAMPUS_CREATED: "campus.created",
  CAMPUS_UPDATED: "campus.updated",
  CAMPUS_STATUS_CHANGED: "campus.status_changed",
  CAMPUS_PRIMARY_CHANGED: "campus.primary_changed",
  CAMPUS_ARCHIVED: "campus.archived",
  CAMPUS_MEMBERSHIP_ADDED: "campus_membership.added",
  CAMPUS_MEMBERSHIP_REMOVED: "campus_membership.removed",
  CAMPUS_MEMBERSHIP_ROLE_CHANGED: "campus_membership.role_changed",
  CAMPUS_MEMBERSHIP_PRIMARY_CHANGED: "campus_membership.primary_changed",
  MEMBER_INVITED: "member.invited",
  MEMBER_PROVISIONED: "member.provisioned",
  INVITATION_RESENT: "invitation.resent",
  INVITATION_REVOKED: "invitation.revoked",
  INVITATION_ACCEPTED: "invitation.accepted",
  MEMBERSHIP_ROLE_CHANGED: "membership.role_changed",
  MEMBERSHIP_SUSPENDED: "membership.suspended",
  MEMBERSHIP_REMOVED: "membership.removed",
  MEMBERSHIP_REACTIVATED: "membership.reactivated",
  OWNERSHIP_TRANSFER_INITIATED: "ownership.transfer_initiated",
  OWNERSHIP_TRANSFER_COMPLETED: "ownership.transfer_completed",
  AUTH_LOGIN: "auth.login",
  INCIDENT_CREATED: "incident.created",
  INCIDENT_UPDATED: "incident.updated",
  INCIDENT_MEMBER_ADDED: "incident.member_added",
  INCIDENT_MEMBER_REMOVED: "incident.member_removed",
  INCIDENT_PHOTO_ADDED: "incident.photo_added",
  INCIDENT_PHOTO_REMOVED: "incident.photo_removed",
  EQUIPMENT_CREATED: "equipment.created",
  EQUIPMENT_UPDATED: "equipment.updated",
  EQUIPMENT_STATUS_CHANGED: "equipment.status_changed",
  EQUIPMENT_ARCHIVED: "equipment.archived",
  EQUIPMENT_RESTORED: "equipment.restored",
  EQUIPMENT_ASSIGNED: "equipment.assigned",
  EQUIPMENT_RETURNED: "equipment.returned",
  EQUIPMENT_REPORTED_LOST: "equipment.reported_lost",
  EQUIPMENT_REPORTED_STOLEN: "equipment.reported_stolen",
  EQUIPMENT_MAINTENANCE_SCHEDULED: "equipment.maintenance_scheduled",
  EQUIPMENT_MAINTENANCE_COMPLETED: "equipment.maintenance_completed",
  EQUIPMENT_INSPECTION_FAILED: "equipment.inspection_failed",
  EQUIPMENT_ATTACHMENT_UPLOADED: "equipment.attachment_uploaded",
  EQUIPMENT_ATTACHMENT_REMOVED: "equipment.attachment_removed",
  EQUIPMENT_RELATIONSHIP_ADDED: "equipment.relationship_added",
  EQUIPMENT_RELATIONSHIP_REMOVED: "equipment.relationship_removed",
  MEDICAL_SUPPLY_CREATED: "medical_supply.created",
  MEDICAL_SUPPLY_UPDATED: "medical_supply.updated",
  MEDICAL_SUPPLY_ARCHIVED: "medical_supply.archived",
  MEDICAL_SUPPLY_RESTORED: "medical_supply.restored",
  MEDICAL_SUPPLY_USED: "medical_supply.used",
  MEDICAL_SUPPLY_USAGE_REMOVED: "medical_supply.usage_removed",
  CERTIFICATION_CREATED: "certification.created",
  CERTIFICATION_UPDATED: "certification.updated",
  CERTIFICATION_ARCHIVED: "certification.archived",
  CERTIFICATION_DELETED: "certification.deleted",
  NOTIFICATION_CREATED: "notification.created",
  NOTIFICATION_QUEUED: "notification.queued",
  NOTIFICATION_CANCELLED: "notification.cancelled",
  NOTIFICATION_ACKNOWLEDGED: "notification.acknowledged",
  NOTIFICATION_DELIVERY_SENT: "notification.delivery_sent",
  NOTIFICATION_DELIVERY_FAILED: "notification.delivery_failed",
  NOTIFICATION_DELIVERY_RETRIED: "notification.delivery_retried",
  NOTIFICATION_PREFERENCES_UPDATED: "notification.preferences_updated",
  NOTIFICATION_SETTINGS_UPDATED: "notification.settings_updated",
  NOTIFICATION_TEMPLATE_CREATED: "notification.template_created",
  NOTIFICATION_TEMPLATE_UPDATED: "notification.template_updated",
  NOTIFICATION_TEMPLATE_RESTORED: "notification.template_restored",
  NOTIFICATION_TEST_EMAIL_SENT: "notification.test_email_sent",
  NOTIFICATION_GROUP_CREATED: "notification_group.created",
  NOTIFICATION_GROUP_UPDATED: "notification_group.updated",
  NOTIFICATION_GROUP_ARCHIVED: "notification_group.archived",
  NOTIFICATION_GROUP_MEMBER_ADDED: "notification_group.member_added",
  NOTIFICATION_GROUP_MEMBER_REMOVED: "notification_group.member_removed",
  NOTIFICATION_GROUP_DEFAULTS_UPDATED: "notification_group.defaults_updated",
  NOTIFICATION_ENDPOINT_ADDED: "notification.endpoint_added",
  NOTIFICATION_ENDPOINT_VERIFIED: "notification.endpoint_verified",
  NOTIFICATION_ENDPOINT_DISABLED: "notification.endpoint_disabled",
  NOTIFICATION_SMS_OPTED_IN: "notification.sms_opted_in",
  NOTIFICATION_SMS_OPTED_OUT: "notification.sms_opted_out",
  POLICY_CREATED: "policy.created",
  POLICY_UPDATED: "policy.updated",
  POLICY_SUBMITTED: "policy.submitted",
  POLICY_CHANGES_REQUESTED: "policy.changes_requested",
  POLICY_APPROVED: "policy.approved",
  POLICY_PUBLISHED: "policy.published",
  POLICY_RETIRED: "policy.retired",
  POLICY_ARCHIVED: "policy.archived",
  POLICY_RESTORED: "policy.restored",
  POLICY_REVISION_STARTED: "policy.revision_started",
  POLICY_ATTACHMENT_UPLOADED: "policy.attachment_uploaded",
  POLICY_ATTACHMENT_REMOVED: "policy.attachment_removed",
  POLICY_ACKNOWLEDGED: "policy.acknowledged",
  POLICY_ACKNOWLEDGMENT_VIEWED: "policy.acknowledgment_viewed",
  POLICY_ACKNOWLEDGMENT_WAIVED: "policy.acknowledgment_waived",
  POLICY_ACKNOWLEDGMENTS_ASSIGNED: "policy.acknowledgments_assigned",
  POLICY_ASSIGNMENT_ADDED: "policy.assignment_added",
  POLICY_ASSIGNMENT_REVOKED: "policy.assignment_revoked",
  SCHEDULE_EVENT_CREATED: "schedule.event_created",
  SCHEDULE_EVENT_UPDATED: "schedule.event_updated",
  SCHEDULE_EVENT_CANCELLED: "schedule.event_cancelled",
  SCHEDULE_EVENT_COMPLETED: "schedule.event_completed",
  SCHEDULE_SHIFT_CREATED: "schedule.shift_created",
  SCHEDULE_SHIFT_UPDATED: "schedule.shift_updated",
  SCHEDULE_SHIFT_CANCELLED: "schedule.shift_cancelled",
  SCHEDULE_ASSIGNMENT_CREATED: "schedule.assignment_created",
  SCHEDULE_ASSIGNMENT_ACCEPTED: "schedule.assignment_accepted",
  SCHEDULE_ASSIGNMENT_DECLINED: "schedule.assignment_declined",
  SCHEDULE_ASSIGNMENT_CANCELLED: "schedule.assignment_cancelled",
  SCHEDULE_ASSIGNMENT_OVERRIDE: "schedule.assignment_override",
  SCHEDULE_UNAVAILABILITY_CREATED: "schedule.unavailability_created",
  SCHEDULE_UNAVAILABILITY_UPDATED: "schedule.unavailability_updated",
  SCHEDULE_UNAVAILABILITY_CANCELLED: "schedule.unavailability_cancelled",
  SCHEDULE_SETTINGS_UPDATED: "schedule.settings_updated",
  SCHEDULE_TEMPLATE_CREATED: "schedule.template_created",
  SCHEDULE_TEMPLATE_UPDATED: "schedule.template_updated",
  SCHEDULE_TEMPLATE_ARCHIVED: "schedule.template_archived",
  SCHEDULE_TEMPLATE_APPLIED: "schedule.template_applied",
} as const;

export type AuditActionName = (typeof AuditAction)[keyof typeof AuditAction];

export const AuditEntityType = {
  CHURCH: "church",
  CAMPUS: "campus",
  CAMPUS_MEMBERSHIP: "campus_membership",
  CHURCH_INVITATION: "church_invitation",
  CHURCH_MEMBERSHIP: "church_membership",
  CHURCH_CONTACT: "church_contact",
  CHURCH_THREAT_LEVEL: "church_threat_level",
  USER: "user",
  INCIDENT: "incident",
  INCIDENT_MEMBER: "incident_member",
  INCIDENT_ATTACHMENT: "incident_attachment",
  SECURITY_EQUIPMENT: "security_equipment",
  EQUIPMENT_ASSIGNMENT: "equipment_assignment",
  EQUIPMENT_MAINTENANCE: "equipment_maintenance",
  EQUIPMENT_ATTACHMENT: "equipment_attachment",
  EQUIPMENT_RELATIONSHIP: "equipment_relationship",
  MEDICAL_SUPPLY: "medical_supply",
  MEDICAL_SUPPLY_USAGE: "medical_supply_usage",
  CERTIFICATION: "certification",
  NOTIFICATION: "notification",
  NOTIFICATION_DELIVERY: "notification_delivery",
  NOTIFICATION_TEMPLATE: "notification_template",
  NOTIFICATION_SETTINGS: "notification_settings",
  NOTIFICATION_GROUP: "notification_group",
  NOTIFICATION_ENDPOINT: "notification_endpoint",
  POLICY_DOCUMENT: "policy_document",
  POLICY_VERSION: "policy_version",
  POLICY_APPROVAL: "policy_approval",
  POLICY_ATTACHMENT: "policy_attachment",
  POLICY_ACKNOWLEDGMENT: "policy_acknowledgment",
  POLICY_ASSIGNMENT: "policy_assignment",
  SCHEDULE_EVENT: "schedule_event",
  SCHEDULE_SHIFT: "schedule_shift",
  SHIFT_ASSIGNMENT: "shift_assignment",
  MEMBER_UNAVAILABILITY: "member_unavailability",
  SCHEDULE_SETTINGS: "schedule_settings",
  SCHEDULE_TEMPLATE: "schedule_template",
} as const;

export type AuditEntityTypeName =
  (typeof AuditEntityType)[keyof typeof AuditEntityType];

export function labelForAuditAction(action: string): string {
  const labels: Record<string, string> = {
    [AuditAction.CHURCH_CREATED]: "Church created",
    [AuditAction.CHURCH_SETTINGS_UPDATED]: "Church settings updated",
    [AuditAction.CHURCH_SETTINGS_GENERAL_UPDATED]: "General settings updated",
    [AuditAction.CHURCH_SETTINGS_CONTACT_UPDATED]: "Contact settings updated",
    [AuditAction.CHURCH_CONTACT_CREATED]: "Church contact created",
    [AuditAction.CHURCH_CONTACT_UPDATED]: "Church contact updated",
    [AuditAction.CHURCH_CONTACT_REMOVED]: "Church contact removed",
    [AuditAction.CHURCH_SETTINGS_ADDRESS_UPDATED]: "Address settings updated",
    [AuditAction.CHURCH_SETTINGS_BRANDING_UPDATED]: "Branding settings updated",
    [AuditAction.CHURCH_SETTINGS_SECURITY_UPDATED]: "Security settings updated",
    [AuditAction.CHURCH_SETTINGS_PREFERENCES_UPDATED]:
      "Application preferences updated",
    [AuditAction.CHURCH_THREAT_LEVEL_UPDATED]: "Threat level updated",
    [AuditAction.CHURCH_LOGO_UPDATED]: "Church logo updated",
    [AuditAction.CHURCH_ACCOUNT_SUSPENDED]: "Church account suspended",
    [AuditAction.CHURCH_ACCOUNT_REACTIVATED]: "Church account reactivated",
    [AuditAction.CHURCH_ACCOUNT_CLOSED]: "Church account closed",
    [AuditAction.CAMPUS_CREATED]: "Campus created",
    [AuditAction.CAMPUS_UPDATED]: "Campus updated",
    [AuditAction.CAMPUS_STATUS_CHANGED]: "Campus status changed",
    [AuditAction.CAMPUS_PRIMARY_CHANGED]: "Primary campus changed",
    [AuditAction.CAMPUS_ARCHIVED]: "Campus archived",
    [AuditAction.CAMPUS_MEMBERSHIP_ADDED]: "Campus membership added",
    [AuditAction.CAMPUS_MEMBERSHIP_REMOVED]: "Campus membership removed",
    [AuditAction.CAMPUS_MEMBERSHIP_ROLE_CHANGED]: "Campus membership role changed",
    [AuditAction.CAMPUS_MEMBERSHIP_PRIMARY_CHANGED]:
      "Campus membership primary changed",
    [AuditAction.MEMBER_INVITED]: "Member invited",
    [AuditAction.MEMBER_PROVISIONED]: "Member provisioned",
    [AuditAction.INVITATION_RESENT]: "Invitation resent",
    [AuditAction.INVITATION_REVOKED]: "Invitation revoked",
    [AuditAction.INVITATION_ACCEPTED]: "Invitation accepted",
    [AuditAction.MEMBERSHIP_ROLE_CHANGED]: "Membership role changed",
    [AuditAction.MEMBERSHIP_SUSPENDED]: "Membership suspended",
    [AuditAction.MEMBERSHIP_REMOVED]: "Membership removed",
    [AuditAction.MEMBERSHIP_REACTIVATED]: "Membership reactivated",
    [AuditAction.OWNERSHIP_TRANSFER_INITIATED]: "Owner transfer initiated",
    [AuditAction.OWNERSHIP_TRANSFER_COMPLETED]: "Owner transfer completed",
    [AuditAction.AUTH_LOGIN]: "User signed in",
    [AuditAction.INCIDENT_CREATED]: "Incident created",
    [AuditAction.INCIDENT_UPDATED]: "Incident updated",
    [AuditAction.INCIDENT_MEMBER_ADDED]: "Incident member added",
    [AuditAction.INCIDENT_MEMBER_REMOVED]: "Incident member removed",
    [AuditAction.INCIDENT_PHOTO_ADDED]: "Incident photo added",
    [AuditAction.INCIDENT_PHOTO_REMOVED]: "Incident photo removed",
    [AuditAction.EQUIPMENT_CREATED]: "Equipment created",
    [AuditAction.EQUIPMENT_UPDATED]: "Equipment updated",
    [AuditAction.EQUIPMENT_STATUS_CHANGED]: "Equipment status changed",
    [AuditAction.EQUIPMENT_ARCHIVED]: "Equipment archived",
    [AuditAction.EQUIPMENT_RESTORED]: "Equipment restored",
    [AuditAction.EQUIPMENT_ASSIGNED]: "Equipment assigned",
    [AuditAction.EQUIPMENT_RETURNED]: "Equipment returned",
    [AuditAction.EQUIPMENT_REPORTED_LOST]: "Equipment reported lost",
    [AuditAction.EQUIPMENT_REPORTED_STOLEN]: "Equipment reported stolen",
    [AuditAction.EQUIPMENT_MAINTENANCE_SCHEDULED]: "Equipment maintenance scheduled",
    [AuditAction.EQUIPMENT_MAINTENANCE_COMPLETED]: "Equipment maintenance completed",
    [AuditAction.EQUIPMENT_INSPECTION_FAILED]: "Equipment inspection failed",
    [AuditAction.EQUIPMENT_ATTACHMENT_UPLOADED]: "Equipment attachment uploaded",
    [AuditAction.EQUIPMENT_ATTACHMENT_REMOVED]: "Equipment attachment removed",
    [AuditAction.EQUIPMENT_RELATIONSHIP_ADDED]: "Equipment relationship added",
    [AuditAction.EQUIPMENT_RELATIONSHIP_REMOVED]: "Equipment relationship removed",
    [AuditAction.MEDICAL_SUPPLY_CREATED]: "Medical supply created",
    [AuditAction.MEDICAL_SUPPLY_UPDATED]: "Medical supply updated",
    [AuditAction.MEDICAL_SUPPLY_ARCHIVED]: "Medical supply archived",
    [AuditAction.MEDICAL_SUPPLY_RESTORED]: "Medical supply restored",
    [AuditAction.MEDICAL_SUPPLY_USED]: "Medical supply used on incident",
    [AuditAction.MEDICAL_SUPPLY_USAGE_REMOVED]: "Medical supply usage removed",
    [AuditAction.CERTIFICATION_CREATED]: "Certification created",
    [AuditAction.CERTIFICATION_UPDATED]: "Certification updated",
    [AuditAction.CERTIFICATION_ARCHIVED]: "Certification archived",
    [AuditAction.CERTIFICATION_DELETED]: "Certification deleted",
    [AuditAction.NOTIFICATION_CREATED]: "Notification created",
    [AuditAction.NOTIFICATION_QUEUED]: "Notification queued",
    [AuditAction.NOTIFICATION_CANCELLED]: "Notification cancelled",
    [AuditAction.NOTIFICATION_ACKNOWLEDGED]: "Notification acknowledged",
    [AuditAction.NOTIFICATION_DELIVERY_SENT]: "Notification delivery sent",
    [AuditAction.NOTIFICATION_DELIVERY_FAILED]: "Notification delivery failed",
    [AuditAction.NOTIFICATION_DELIVERY_RETRIED]: "Notification delivery retried",
    [AuditAction.NOTIFICATION_PREFERENCES_UPDATED]:
      "Notification preferences updated",
    [AuditAction.NOTIFICATION_SETTINGS_UPDATED]:
      "Notification settings updated",
    [AuditAction.NOTIFICATION_TEMPLATE_CREATED]: "Notification template created",
    [AuditAction.NOTIFICATION_TEMPLATE_UPDATED]: "Notification template updated",
    [AuditAction.NOTIFICATION_TEMPLATE_RESTORED]:
      "Notification template restored",
    [AuditAction.NOTIFICATION_TEST_EMAIL_SENT]: "Test notification email sent",
    [AuditAction.NOTIFICATION_GROUP_CREATED]: "Notification group created",
    [AuditAction.NOTIFICATION_GROUP_UPDATED]: "Notification group updated",
    [AuditAction.NOTIFICATION_GROUP_ARCHIVED]: "Notification group archived",
    [AuditAction.NOTIFICATION_GROUP_MEMBER_ADDED]:
      "Notification group member added",
    [AuditAction.NOTIFICATION_GROUP_MEMBER_REMOVED]:
      "Notification group member removed",
    [AuditAction.NOTIFICATION_GROUP_DEFAULTS_UPDATED]:
      "Notification group defaults updated",
    [AuditAction.NOTIFICATION_ENDPOINT_ADDED]: "Notification endpoint added",
    [AuditAction.NOTIFICATION_ENDPOINT_VERIFIED]:
      "Notification endpoint verified",
    [AuditAction.NOTIFICATION_ENDPOINT_DISABLED]:
      "Notification endpoint disabled",
    [AuditAction.NOTIFICATION_SMS_OPTED_IN]: "SMS notifications opted in",
    [AuditAction.NOTIFICATION_SMS_OPTED_OUT]: "SMS notifications opted out",
    [AuditAction.POLICY_CREATED]: "Policy created",
    [AuditAction.POLICY_UPDATED]: "Policy updated",
    [AuditAction.POLICY_SUBMITTED]: "Policy submitted for review",
    [AuditAction.POLICY_CHANGES_REQUESTED]: "Policy changes requested",
    [AuditAction.POLICY_APPROVED]: "Policy approved",
    [AuditAction.POLICY_PUBLISHED]: "Policy published",
    [AuditAction.POLICY_RETIRED]: "Policy retired",
    [AuditAction.POLICY_ARCHIVED]: "Policy archived",
    [AuditAction.POLICY_RESTORED]: "Policy restored",
    [AuditAction.POLICY_REVISION_STARTED]: "Policy revision started",
    [AuditAction.POLICY_ATTACHMENT_UPLOADED]: "Policy attachment uploaded",
    [AuditAction.POLICY_ATTACHMENT_REMOVED]: "Policy attachment removed",
    [AuditAction.POLICY_ACKNOWLEDGED]: "Policy acknowledged",
    [AuditAction.POLICY_ACKNOWLEDGMENT_VIEWED]: "Policy acknowledgment viewed",
    [AuditAction.POLICY_ACKNOWLEDGMENT_WAIVED]: "Policy acknowledgment waived",
    [AuditAction.POLICY_ACKNOWLEDGMENTS_ASSIGNED]:
      "Policy acknowledgments assigned",
    [AuditAction.POLICY_ASSIGNMENT_ADDED]: "Policy assignment added",
    [AuditAction.POLICY_ASSIGNMENT_REVOKED]: "Policy assignment revoked",
    [AuditAction.SCHEDULE_EVENT_CREATED]: "Schedule event created",
    [AuditAction.SCHEDULE_EVENT_UPDATED]: "Schedule event updated",
    [AuditAction.SCHEDULE_EVENT_CANCELLED]: "Schedule event cancelled",
    [AuditAction.SCHEDULE_EVENT_COMPLETED]: "Schedule event completed",
    [AuditAction.SCHEDULE_SHIFT_CREATED]: "Schedule shift created",
    [AuditAction.SCHEDULE_SHIFT_UPDATED]: "Schedule shift updated",
    [AuditAction.SCHEDULE_SHIFT_CANCELLED]: "Schedule shift cancelled",
    [AuditAction.SCHEDULE_ASSIGNMENT_CREATED]: "Shift assignment created",
    [AuditAction.SCHEDULE_ASSIGNMENT_ACCEPTED]: "Shift assignment accepted",
    [AuditAction.SCHEDULE_ASSIGNMENT_DECLINED]: "Shift assignment declined",
    [AuditAction.SCHEDULE_ASSIGNMENT_CANCELLED]: "Shift assignment cancelled",
    [AuditAction.SCHEDULE_ASSIGNMENT_OVERRIDE]: "Shift assignment conflict override",
    [AuditAction.SCHEDULE_UNAVAILABILITY_CREATED]: "Unavailability created",
    [AuditAction.SCHEDULE_UNAVAILABILITY_UPDATED]: "Unavailability updated",
    [AuditAction.SCHEDULE_UNAVAILABILITY_CANCELLED]: "Unavailability cancelled",
    [AuditAction.SCHEDULE_SETTINGS_UPDATED]: "Scheduling settings updated",
    [AuditAction.SCHEDULE_TEMPLATE_CREATED]: "Schedule template created",
    [AuditAction.SCHEDULE_TEMPLATE_UPDATED]: "Schedule template updated",
    [AuditAction.SCHEDULE_TEMPLATE_ARCHIVED]: "Schedule template archived",
    [AuditAction.SCHEDULE_TEMPLATE_APPLIED]: "Schedule template applied",
    // Legacy rows from earlier phases
    "membership.invitation_created": "Member invited",
    "membership.invitation_accepted": "Invitation accepted",
    "membership.status_changed": "Membership status changed",
  };
  return labels[action] ?? action;
}
