/**
 * Canonical audit action names for Sanctuary Protected.
 * Prefer these constants everywhere — do not invent ad-hoc strings.
 */
export const AuditAction = {
  CHURCH_CREATED: "church.created",
  CHURCH_SETTINGS_UPDATED: "church.settings_updated",
  CHURCH_SETTINGS_GENERAL_UPDATED: "church.settings.general_updated",
  CHURCH_SETTINGS_CONTACT_UPDATED: "church.settings.contact_updated",
  CHURCH_CONTACT_CREATED: "church.contact_created",
  CHURCH_CONTACT_UPDATED: "church.contact_updated",
  CHURCH_CONTACT_REMOVED: "church.contact_removed",
  CHURCH_SETTINGS_ADDRESS_UPDATED: "church.settings.address_updated",
  CHURCH_SETTINGS_BRANDING_UPDATED: "church.settings.branding_updated",
  CHURCH_SETTINGS_SECURITY_UPDATED: "church.settings.security_updated",
  CHURCH_SETTINGS_PREFERENCES_UPDATED: "church.settings.preferences_updated",
  CHURCH_LOGO_UPDATED: "church.logo_updated",
  CHURCH_ACCOUNT_SUSPENDED: "church.account_suspended",
  CHURCH_ACCOUNT_REACTIVATED: "church.account_reactivated",
  CHURCH_ACCOUNT_CLOSED: "church.account_closed",
  CAMPUS_CREATED: "campus.created",
  CAMPUS_UPDATED: "campus.updated",
  MEMBER_INVITED: "member.invited",
  MEMBER_PROVISIONED: "member.provisioned",
  INVITATION_RESENT: "invitation.resent",
  INVITATION_REVOKED: "invitation.revoked",
  INVITATION_ACCEPTED: "invitation.accepted",
  MEMBERSHIP_ROLE_CHANGED: "membership.role_changed",
  MEMBERSHIP_SUSPENDED: "membership.suspended",
  MEMBERSHIP_REMOVED: "membership.removed",
  MEMBERSHIP_REACTIVATED: "membership.reactivated",
  OWNERSHIP_TRANSFER_INITIATED: "ownership.transfer_initiated",
  OWNERSHIP_TRANSFER_COMPLETED: "ownership.transfer_completed",
  AUTH_LOGIN: "auth.login",
  INCIDENT_CREATED: "incident.created",
  INCIDENT_UPDATED: "incident.updated",
  INCIDENT_MEMBER_ADDED: "incident.member_added",
  INCIDENT_MEMBER_REMOVED: "incident.member_removed",
  INCIDENT_PHOTO_ADDED: "incident.photo_added",
  INCIDENT_PHOTO_REMOVED: "incident.photo_removed",
  EQUIPMENT_CREATED: "equipment.created",
  EQUIPMENT_UPDATED: "equipment.updated",
  EQUIPMENT_STATUS_CHANGED: "equipment.status_changed",
  EQUIPMENT_ARCHIVED: "equipment.archived",
  EQUIPMENT_RESTORED: "equipment.restored",
  EQUIPMENT_ASSIGNED: "equipment.assigned",
  EQUIPMENT_RETURNED: "equipment.returned",
  EQUIPMENT_REPORTED_LOST: "equipment.reported_lost",
  EQUIPMENT_REPORTED_STOLEN: "equipment.reported_stolen",
  EQUIPMENT_MAINTENANCE_SCHEDULED: "equipment.maintenance_scheduled",
  EQUIPMENT_MAINTENANCE_COMPLETED: "equipment.maintenance_completed",
  EQUIPMENT_INSPECTION_FAILED: "equipment.inspection_failed",
  EQUIPMENT_ATTACHMENT_UPLOADED: "equipment.attachment_uploaded",
  EQUIPMENT_ATTACHMENT_REMOVED: "equipment.attachment_removed",
  EQUIPMENT_RELATIONSHIP_ADDED: "equipment.relationship_added",
  EQUIPMENT_RELATIONSHIP_REMOVED: "equipment.relationship_removed",
  MEDICAL_SUPPLY_CREATED: "medical_supply.created",
  MEDICAL_SUPPLY_UPDATED: "medical_supply.updated",
  MEDICAL_SUPPLY_ARCHIVED: "medical_supply.archived",
  MEDICAL_SUPPLY_RESTORED: "medical_supply.restored",
  MEDICAL_SUPPLY_USED: "medical_supply.used",
  MEDICAL_SUPPLY_USAGE_REMOVED: "medical_supply.usage_removed",
  CERTIFICATION_CREATED: "certification.created",
  CERTIFICATION_UPDATED: "certification.updated",
  CERTIFICATION_ARCHIVED: "certification.archived",
  CERTIFICATION_DELETED: "certification.deleted",
} as const;

export type AuditActionName = (typeof AuditAction)[keyof typeof AuditAction];

export const AuditEntityType = {
  CHURCH: "church",
  CAMPUS: "campus",
  CHURCH_INVITATION: "church_invitation",
  CHURCH_MEMBERSHIP: "church_membership",
  CHURCH_CONTACT: "church_contact",
  USER: "user",
  INCIDENT: "incident",
  INCIDENT_MEMBER: "incident_member",
  INCIDENT_ATTACHMENT: "incident_attachment",
  SECURITY_EQUIPMENT: "security_equipment",
  EQUIPMENT_ASSIGNMENT: "equipment_assignment",
  EQUIPMENT_MAINTENANCE: "equipment_maintenance",
  EQUIPMENT_ATTACHMENT: "equipment_attachment",
  EQUIPMENT_RELATIONSHIP: "equipment_relationship",
  MEDICAL_SUPPLY: "medical_supply",
  MEDICAL_SUPPLY_USAGE: "medical_supply_usage",
  CERTIFICATION: "certification",
} as const;

export type AuditEntityTypeName =
  (typeof AuditEntityType)[keyof typeof AuditEntityType];

export function labelForAuditAction(action: string): string {
  const labels: Record<string, string> = {
    [AuditAction.CHURCH_CREATED]: "Church created",
    [AuditAction.CHURCH_SETTINGS_UPDATED]: "Church settings updated",
    [AuditAction.CHURCH_SETTINGS_GENERAL_UPDATED]: "General settings updated",
    [AuditAction.CHURCH_SETTINGS_CONTACT_UPDATED]: "Contact settings updated",
    [AuditAction.CHURCH_CONTACT_CREATED]: "Church contact created",
    [AuditAction.CHURCH_CONTACT_UPDATED]: "Church contact updated",
    [AuditAction.CHURCH_CONTACT_REMOVED]: "Church contact removed",
    [AuditAction.CHURCH_SETTINGS_ADDRESS_UPDATED]: "Address settings updated",
    [AuditAction.CHURCH_SETTINGS_BRANDING_UPDATED]: "Branding settings updated",
    [AuditAction.CHURCH_SETTINGS_SECURITY_UPDATED]: "Security settings updated",
    [AuditAction.CHURCH_SETTINGS_PREFERENCES_UPDATED]:
      "Application preferences updated",
    [AuditAction.CHURCH_LOGO_UPDATED]: "Church logo updated",
    [AuditAction.CHURCH_ACCOUNT_SUSPENDED]: "Church account suspended",
    [AuditAction.CHURCH_ACCOUNT_REACTIVATED]: "Church account reactivated",
    [AuditAction.CHURCH_ACCOUNT_CLOSED]: "Church account closed",
    [AuditAction.CAMPUS_CREATED]: "Campus created",
    [AuditAction.CAMPUS_UPDATED]: "Campus updated",
    [AuditAction.MEMBER_INVITED]: "Member invited",
    [AuditAction.MEMBER_PROVISIONED]: "Member provisioned",
    [AuditAction.INVITATION_RESENT]: "Invitation resent",
    [AuditAction.INVITATION_REVOKED]: "Invitation revoked",
    [AuditAction.INVITATION_ACCEPTED]: "Invitation accepted",
    [AuditAction.MEMBERSHIP_ROLE_CHANGED]: "Membership role changed",
    [AuditAction.MEMBERSHIP_SUSPENDED]: "Membership suspended",
    [AuditAction.MEMBERSHIP_REMOVED]: "Membership removed",
    [AuditAction.MEMBERSHIP_REACTIVATED]: "Membership reactivated",
    [AuditAction.OWNERSHIP_TRANSFER_INITIATED]: "Owner transfer initiated",
    [AuditAction.OWNERSHIP_TRANSFER_COMPLETED]: "Owner transfer completed",
    [AuditAction.AUTH_LOGIN]: "User signed in",
    [AuditAction.INCIDENT_CREATED]: "Incident created",
    [AuditAction.INCIDENT_UPDATED]: "Incident updated",
    [AuditAction.INCIDENT_MEMBER_ADDED]: "Incident member added",
    [AuditAction.INCIDENT_MEMBER_REMOVED]: "Incident member removed",
    [AuditAction.INCIDENT_PHOTO_ADDED]: "Incident photo added",
    [AuditAction.INCIDENT_PHOTO_REMOVED]: "Incident photo removed",
    [AuditAction.EQUIPMENT_CREATED]: "Equipment created",
    [AuditAction.EQUIPMENT_UPDATED]: "Equipment updated",
    [AuditAction.EQUIPMENT_STATUS_CHANGED]: "Equipment status changed",
    [AuditAction.EQUIPMENT_ARCHIVED]: "Equipment archived",
    [AuditAction.EQUIPMENT_RESTORED]: "Equipment restored",
    [AuditAction.EQUIPMENT_ASSIGNED]: "Equipment assigned",
    [AuditAction.EQUIPMENT_RETURNED]: "Equipment returned",
    [AuditAction.EQUIPMENT_REPORTED_LOST]: "Equipment reported lost",
    [AuditAction.EQUIPMENT_REPORTED_STOLEN]: "Equipment reported stolen",
    [AuditAction.EQUIPMENT_MAINTENANCE_SCHEDULED]: "Equipment maintenance scheduled",
    [AuditAction.EQUIPMENT_MAINTENANCE_COMPLETED]: "Equipment maintenance completed",
    [AuditAction.EQUIPMENT_INSPECTION_FAILED]: "Equipment inspection failed",
    [AuditAction.EQUIPMENT_ATTACHMENT_UPLOADED]: "Equipment attachment uploaded",
    [AuditAction.EQUIPMENT_ATTACHMENT_REMOVED]: "Equipment attachment removed",
    [AuditAction.EQUIPMENT_RELATIONSHIP_ADDED]: "Equipment relationship added",
    [AuditAction.EQUIPMENT_RELATIONSHIP_REMOVED]: "Equipment relationship removed",
    [AuditAction.MEDICAL_SUPPLY_CREATED]: "Medical supply created",
    [AuditAction.MEDICAL_SUPPLY_UPDATED]: "Medical supply updated",
    [AuditAction.MEDICAL_SUPPLY_ARCHIVED]: "Medical supply archived",
    [AuditAction.MEDICAL_SUPPLY_RESTORED]: "Medical supply restored",
    [AuditAction.MEDICAL_SUPPLY_USED]: "Medical supply used on incident",
    [AuditAction.MEDICAL_SUPPLY_USAGE_REMOVED]: "Medical supply usage removed",
    [AuditAction.CERTIFICATION_CREATED]: "Certification created",
    [AuditAction.CERTIFICATION_UPDATED]: "Certification updated",
    [AuditAction.CERTIFICATION_ARCHIVED]: "Certification archived",
    [AuditAction.CERTIFICATION_DELETED]: "Certification deleted",
    // Legacy rows from earlier phases
    "membership.invitation_created": "Member invited",
    "membership.invitation_accepted": "Invitation accepted",
    "membership.status_changed": "Membership status changed",
  };
  return labels[action] ?? action;
}
