/**
 * lib/security/permission-keys.ts
 *
 * Stable application permission keys.
 * These match the permission_key values in the permission_definitions table.
 */

export const PERMISSION_KEYS = {
  // Dashboard
  DASHBOARD_VIEW: "dashboard.view",

  // Members / Users
  MEMBERS_VIEW: "members.view",
  MEMBERS_CREATE: "members.create",
  MEMBERS_EDIT: "members.edit",
  MEMBERS_DEACTIVATE: "members.deactivate",

  // Security Groups
  GROUPS_VIEW: "groups.view",
  GROUPS_CREATE: "groups.create",
  GROUPS_EDIT: "groups.edit",
  GROUPS_DELETE: "groups.delete",
  GROUPS_MANAGE: "groups.manage",
  GROUPS_MANAGE_MEMBERS: "groups.manage_members",

  // Incidents
  INCIDENTS_VIEW: "incidents.view",
  INCIDENTS_CREATE: "incidents.create",
  INCIDENTS_EDIT: "incidents.edit",
  INCIDENTS_DELETE: "incidents.delete",
  INCIDENTS_EXPORT: "incidents.export",
  INCIDENTS_VIEW_SENSITIVE: "incidents.view_sensitive",
  INCIDENTS_EDIT_SENSITIVE: "incidents.edit_sensitive",
  INCIDENTS_VIEW_ALL_CAMPUSES: "incidents.view_all_campuses",
  INCIDENTS_DELETE_ARCHIVE: "incidents.delete_archive",

  // Reports
  REPORTS_VIEW: "reports.view",
  REPORTS_RUN: "reports.run",
  REPORTS_SAVE: "reports.save",
  REPORTS_EDIT: "reports.edit",
  REPORTS_DELETE: "reports.delete",
  REPORTS_EXPORT: "reports.export",
  REPORTS_SCHEDULE: "reports.schedule",
  REPORTS_MANAGE_DEFINITIONS: "reports.manage_definitions",
  REPORTS_VIEW_ALL_CAMPUSES: "reports.view_all_campuses",

  // Cameras
  CAMERAS_VIEW_LIVE: "cameras.view_live",
  CAMERAS_VIEW_RECORDINGS: "cameras.view_recordings",
  CAMERAS_DOWNLOAD_RECORDINGS: "cameras.download_recordings",
  CAMERAS_MANAGE: "cameras.manage",

  // Notifications
  NOTIFICATIONS_SEND: "notifications.send",
  NOTIFICATIONS_SEND_EMERGENCY: "notifications.send_emergency",
  NOTIFICATIONS_MANAGE_TEMPLATES: "notifications.manage_templates",

  // Events
  EVENTS_VIEW: "events.view",
  EVENTS_CREATE: "events.create",
  EVENTS_EDIT: "events.edit",
  EVENTS_ASSIGN_TEAM: "events.assign_team",
  EVENTS_MANAGE: "events.manage",

  // Policies
  POLICIES_VIEW: "policies.view",
  POLICIES_CREATE: "policies.create",
  POLICIES_EDIT: "policies.edit",
  POLICIES_PUBLISH: "policies.publish",

  // Training & Certifications
  TRAINING_VIEW: "training.view",
  TRAINING_MANAGE: "training.manage",
  CERTIFICATIONS_VIEW: "certifications.view",
  CERTIFICATIONS_MANAGE: "certifications.manage",

  // Equipment
  EQUIPMENT_VIEW: "equipment.view",
  EQUIPMENT_MANAGE: "equipment.manage",

  // Campuses
  CAMPUSES_VIEW: "campuses.view",
  CAMPUSES_MANAGE: "campuses.manage",

  // Security Administration
  SECURITY_VIEW: "security.view",
  SECURITY_MANAGE_GROUPS: "security.manage_groups",
  SECURITY_MANAGE_USERS: "security.manage_users",
  SECURITY_GRANT_DIRECT_PERMISSIONS: "security.grant_direct_permissions",
  SECURITY_MANAGE_TEMPORARY_ACCESS: "security.manage_temporary_access",
  SECURITY_VIEW_AUDIT_LOG: "security.view_audit_log",
  SECURITY_PREVIEW_ACCESS: "security.preview_access",

  // Church Settings
  CHURCH_SETTINGS_VIEW: "church_settings.view",
  CHURCH_SETTINGS_MANAGE: "church_settings.manage",
} as const;

export type PermissionKey = (typeof PERMISSION_KEYS)[keyof typeof PERMISSION_KEYS];

const PERMISSION_KEY_LIST: readonly PermissionKey[] = Object.values(PERMISSION_KEYS);

export function isPermissionKey(value: string): value is PermissionKey {
  return PERMISSION_KEY_LIST.includes(value as PermissionKey);
}

/**
 * Role-to-permission mappings for backward compatibility.
 * Maps existing church roles to sets of permissions they should have.
 */
export const ROLE_PERMISSION_MAPPING: Record<string, PermissionKey[]> = {
  viewer: [
    PERMISSION_KEYS.DASHBOARD_VIEW,
    PERMISSION_KEYS.MEMBERS_VIEW,
    PERMISSION_KEYS.INCIDENTS_VIEW,
    PERMISSION_KEYS.REPORTS_VIEW,
    PERMISSION_KEYS.EVENTS_VIEW,
    PERMISSION_KEYS.POLICIES_VIEW,
    PERMISSION_KEYS.CAMPUSES_VIEW,
    PERMISSION_KEYS.CERTIFICATIONS_VIEW,
    PERMISSION_KEYS.CHURCH_SETTINGS_VIEW,
  ],

  security_member: [
    PERMISSION_KEYS.DASHBOARD_VIEW,
    PERMISSION_KEYS.MEMBERS_VIEW,
    PERMISSION_KEYS.INCIDENTS_VIEW,
    PERMISSION_KEYS.INCIDENTS_CREATE,
    PERMISSION_KEYS.EVENTS_VIEW,
    PERMISSION_KEYS.REPORTS_VIEW,
    PERMISSION_KEYS.POLICIES_VIEW,
    PERMISSION_KEYS.CAMPUSES_VIEW,
    PERMISSION_KEYS.CERTIFICATIONS_VIEW,
    PERMISSION_KEYS.CHURCH_SETTINGS_VIEW,
  ],

  security_leader: [
    PERMISSION_KEYS.DASHBOARD_VIEW,
    PERMISSION_KEYS.MEMBERS_VIEW,
    PERMISSION_KEYS.INCIDENTS_VIEW,
    PERMISSION_KEYS.INCIDENTS_CREATE,
    PERMISSION_KEYS.INCIDENTS_EDIT,
    PERMISSION_KEYS.EVENTS_VIEW,
    PERMISSION_KEYS.EVENTS_EDIT,
    PERMISSION_KEYS.EVENTS_ASSIGN_TEAM,
    PERMISSION_KEYS.POLICIES_VIEW,
    PERMISSION_KEYS.NOTIFICATIONS_SEND,
    PERMISSION_KEYS.REPORTS_VIEW,
    PERMISSION_KEYS.REPORTS_RUN,
    PERMISSION_KEYS.CAMPUSES_VIEW,
    PERMISSION_KEYS.CERTIFICATIONS_VIEW,
    PERMISSION_KEYS.EQUIPMENT_VIEW,
    PERMISSION_KEYS.CHURCH_SETTINGS_VIEW,
  ],

  administrator: [
    PERMISSION_KEYS.DASHBOARD_VIEW,
    PERMISSION_KEYS.MEMBERS_VIEW,
    PERMISSION_KEYS.MEMBERS_CREATE,
    PERMISSION_KEYS.MEMBERS_EDIT,
    PERMISSION_KEYS.MEMBERS_DEACTIVATE,
    PERMISSION_KEYS.INCIDENTS_VIEW,
    PERMISSION_KEYS.INCIDENTS_CREATE,
    PERMISSION_KEYS.INCIDENTS_EDIT,
    PERMISSION_KEYS.INCIDENTS_EXPORT,
    PERMISSION_KEYS.INCIDENTS_VIEW_SENSITIVE,
    PERMISSION_KEYS.INCIDENTS_EDIT_SENSITIVE,
    PERMISSION_KEYS.EVENTS_VIEW,
    PERMISSION_KEYS.EVENTS_CREATE,
    PERMISSION_KEYS.EVENTS_EDIT,
    PERMISSION_KEYS.EVENTS_ASSIGN_TEAM,
    PERMISSION_KEYS.EVENTS_MANAGE,
    PERMISSION_KEYS.POLICIES_VIEW,
    PERMISSION_KEYS.POLICIES_CREATE,
    PERMISSION_KEYS.POLICIES_EDIT,
    PERMISSION_KEYS.POLICIES_PUBLISH,
    PERMISSION_KEYS.NOTIFICATIONS_SEND,
    PERMISSION_KEYS.REPORTS_VIEW,
    PERMISSION_KEYS.REPORTS_RUN,
    PERMISSION_KEYS.REPORTS_SAVE,
    PERMISSION_KEYS.REPORTS_EXPORT,
    PERMISSION_KEYS.REPORTS_EDIT,
    PERMISSION_KEYS.CAMPUSES_VIEW,
    PERMISSION_KEYS.CAMPUSES_MANAGE,
    PERMISSION_KEYS.CERTIFICATIONS_VIEW,
    PERMISSION_KEYS.CERTIFICATIONS_MANAGE,
    PERMISSION_KEYS.EQUIPMENT_VIEW,
    PERMISSION_KEYS.EQUIPMENT_MANAGE,
    PERMISSION_KEYS.TRAINING_VIEW,
    PERMISSION_KEYS.TRAINING_MANAGE,
    PERMISSION_KEYS.CHURCH_SETTINGS_VIEW,
    PERMISSION_KEYS.CHURCH_SETTINGS_MANAGE,
    PERMISSION_KEYS.SECURITY_VIEW,
  ],

  co_owner: [
    PERMISSION_KEYS.DASHBOARD_VIEW,
    PERMISSION_KEYS.MEMBERS_VIEW,
    PERMISSION_KEYS.MEMBERS_CREATE,
    PERMISSION_KEYS.MEMBERS_EDIT,
    PERMISSION_KEYS.MEMBERS_DEACTIVATE,
    PERMISSION_KEYS.INCIDENTS_VIEW,
    PERMISSION_KEYS.INCIDENTS_CREATE,
    PERMISSION_KEYS.INCIDENTS_EDIT,
    PERMISSION_KEYS.INCIDENTS_DELETE,
    PERMISSION_KEYS.INCIDENTS_DELETE_ARCHIVE,
    PERMISSION_KEYS.INCIDENTS_EXPORT,
    PERMISSION_KEYS.INCIDENTS_VIEW_SENSITIVE,
    PERMISSION_KEYS.INCIDENTS_EDIT_SENSITIVE,
    PERMISSION_KEYS.INCIDENTS_VIEW_ALL_CAMPUSES,
    PERMISSION_KEYS.EVENTS_VIEW,
    PERMISSION_KEYS.EVENTS_CREATE,
    PERMISSION_KEYS.EVENTS_EDIT,
    PERMISSION_KEYS.EVENTS_ASSIGN_TEAM,
    PERMISSION_KEYS.EVENTS_MANAGE,
    PERMISSION_KEYS.POLICIES_VIEW,
    PERMISSION_KEYS.POLICIES_CREATE,
    PERMISSION_KEYS.POLICIES_EDIT,
    PERMISSION_KEYS.POLICIES_PUBLISH,
    PERMISSION_KEYS.NOTIFICATIONS_SEND,
    PERMISSION_KEYS.NOTIFICATIONS_SEND_EMERGENCY,
    PERMISSION_KEYS.CAMERAS_VIEW_LIVE,
    PERMISSION_KEYS.REPORTS_VIEW,
    PERMISSION_KEYS.REPORTS_RUN,
    PERMISSION_KEYS.REPORTS_SAVE,
    PERMISSION_KEYS.REPORTS_EXPORT,
    PERMISSION_KEYS.REPORTS_EDIT,
    PERMISSION_KEYS.REPORTS_DELETE,
    PERMISSION_KEYS.REPORTS_SCHEDULE,
    PERMISSION_KEYS.REPORTS_MANAGE_DEFINITIONS,
    PERMISSION_KEYS.REPORTS_VIEW_ALL_CAMPUSES,
    PERMISSION_KEYS.CAMPUSES_VIEW,
    PERMISSION_KEYS.CAMPUSES_MANAGE,
    PERMISSION_KEYS.CERTIFICATIONS_VIEW,
    PERMISSION_KEYS.CERTIFICATIONS_MANAGE,
    PERMISSION_KEYS.EQUIPMENT_VIEW,
    PERMISSION_KEYS.EQUIPMENT_MANAGE,
    PERMISSION_KEYS.TRAINING_VIEW,
    PERMISSION_KEYS.TRAINING_MANAGE,
    PERMISSION_KEYS.CHURCH_SETTINGS_VIEW,
    PERMISSION_KEYS.CHURCH_SETTINGS_MANAGE,
    PERMISSION_KEYS.SECURITY_VIEW,
    PERMISSION_KEYS.SECURITY_MANAGE_GROUPS,
    PERMISSION_KEYS.SECURITY_MANAGE_USERS,
    PERMISSION_KEYS.SECURITY_GRANT_DIRECT_PERMISSIONS,
    PERMISSION_KEYS.SECURITY_MANAGE_TEMPORARY_ACCESS,
    PERMISSION_KEYS.SECURITY_VIEW_AUDIT_LOG,
    PERMISSION_KEYS.SECURITY_PREVIEW_ACCESS,
  ],

  owner: [
    PERMISSION_KEYS.DASHBOARD_VIEW,
    PERMISSION_KEYS.MEMBERS_VIEW,
    PERMISSION_KEYS.MEMBERS_CREATE,
    PERMISSION_KEYS.MEMBERS_EDIT,
    PERMISSION_KEYS.MEMBERS_DEACTIVATE,
    PERMISSION_KEYS.INCIDENTS_VIEW,
    PERMISSION_KEYS.INCIDENTS_CREATE,
    PERMISSION_KEYS.INCIDENTS_EDIT,
    PERMISSION_KEYS.INCIDENTS_DELETE,
    PERMISSION_KEYS.INCIDENTS_DELETE_ARCHIVE,
    PERMISSION_KEYS.INCIDENTS_EXPORT,
    PERMISSION_KEYS.INCIDENTS_VIEW_SENSITIVE,
    PERMISSION_KEYS.INCIDENTS_EDIT_SENSITIVE,
    PERMISSION_KEYS.INCIDENTS_VIEW_ALL_CAMPUSES,
    PERMISSION_KEYS.EVENTS_VIEW,
    PERMISSION_KEYS.EVENTS_CREATE,
    PERMISSION_KEYS.EVENTS_EDIT,
    PERMISSION_KEYS.EVENTS_ASSIGN_TEAM,
    PERMISSION_KEYS.EVENTS_MANAGE,
    PERMISSION_KEYS.POLICIES_VIEW,
    PERMISSION_KEYS.POLICIES_CREATE,
    PERMISSION_KEYS.POLICIES_EDIT,
    PERMISSION_KEYS.POLICIES_PUBLISH,
    PERMISSION_KEYS.NOTIFICATIONS_SEND,
    PERMISSION_KEYS.NOTIFICATIONS_SEND_EMERGENCY,
    PERMISSION_KEYS.CAMERAS_VIEW_LIVE,
    PERMISSION_KEYS.CAMERAS_VIEW_RECORDINGS,
    PERMISSION_KEYS.CAMERAS_DOWNLOAD_RECORDINGS,
    PERMISSION_KEYS.CAMERAS_MANAGE,
    PERMISSION_KEYS.REPORTS_VIEW,
    PERMISSION_KEYS.REPORTS_RUN,
    PERMISSION_KEYS.REPORTS_SAVE,
    PERMISSION_KEYS.REPORTS_EXPORT,
    PERMISSION_KEYS.REPORTS_EDIT,
    PERMISSION_KEYS.REPORTS_DELETE,
    PERMISSION_KEYS.REPORTS_SCHEDULE,
    PERMISSION_KEYS.REPORTS_MANAGE_DEFINITIONS,
    PERMISSION_KEYS.REPORTS_VIEW_ALL_CAMPUSES,
    PERMISSION_KEYS.CAMPUSES_VIEW,
    PERMISSION_KEYS.CAMPUSES_MANAGE,
    PERMISSION_KEYS.CERTIFICATIONS_VIEW,
    PERMISSION_KEYS.CERTIFICATIONS_MANAGE,
    PERMISSION_KEYS.EQUIPMENT_VIEW,
    PERMISSION_KEYS.EQUIPMENT_MANAGE,
    PERMISSION_KEYS.TRAINING_VIEW,
    PERMISSION_KEYS.TRAINING_MANAGE,
    PERMISSION_KEYS.CHURCH_SETTINGS_VIEW,
    PERMISSION_KEYS.CHURCH_SETTINGS_MANAGE,
    PERMISSION_KEYS.SECURITY_VIEW,
    PERMISSION_KEYS.SECURITY_MANAGE_GROUPS,
    PERMISSION_KEYS.SECURITY_MANAGE_USERS,
    PERMISSION_KEYS.SECURITY_GRANT_DIRECT_PERMISSIONS,
    PERMISSION_KEYS.SECURITY_MANAGE_TEMPORARY_ACCESS,
    PERMISSION_KEYS.SECURITY_VIEW_AUDIT_LOG,
    PERMISSION_KEYS.SECURITY_PREVIEW_ACCESS,
  ],
};
